-- 087: [int].factSoliscloudEnergyAndPowerPv -- version Silver de
-- stg.factSoliscloudEnergyAndPowerPv (dominio Solar). Entidad ABP con
-- telemetria cruda del inversor en un campo JSON (KpiData, ~128 claves:
-- voltajes/corrientes por string PV1-32, fases AC, bateria, etc.) --
-- confirmado shape consistente en los 16107 registros actuales. Por
-- decision del usuario (2026-09-21) se aplanan TODAS las claves a columnas
-- DECIMAL(18,4)/NVARCHAR tipadas (no solo un subconjunto curado, a
-- diferencia de factHuaweiEnergyAndPowerPv que solo tenia 3 claves). Se
-- conserva ademas el JSON crudo (KpiDataRaw) por si el origen agrega mas
-- claves a futuro. Time llega como epoch en milisegundos -- se tipa a
-- DATETIME2 (el campo JSON "time"/"timeStr" son la hora local del inversor
-- tal cual la reporta el equipo, se preservan aparte como KpiTime/TimeStr
-- sin fusionar con la columna Time ya convertida). Carga INCREMENTAL por
-- watermark (comparacion truncada a milisegundo), igual que los demas
-- facts del dominio Solar.

IF NOT EXISTS (
    SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = 'int' AND t.name = 'factSoliscloudEnergyAndPowerPv'
)
BEGIN
    CREATE TABLE [int].factSoliscloudEnergyAndPowerPv (
        Id                     BIGINT         NOT NULL CONSTRAINT PK_Int_factSoliscloudEnergyAndPowerPv PRIMARY KEY,
        DeviceId                NVARCHAR(200)  NOT NULL,
        Time                     DATETIME2(7)   NOT NULL,
        AcOutputType                 DECIMAL(18,4)  NULL,
        BatteryCapacitySoc           DECIMAL(18,4)  NULL,
        BatteryChargingCurrent       DECIMAL(18,4)  NULL,
        BatteryDischargeLimiting     DECIMAL(18,4)  NULL,
        BatteryHealthSoh             DECIMAL(18,4)  NULL,
        BatteryPower                 DECIMAL(18,4)  NULL,
        BatteryTodayChargeEnergy     DECIMAL(18,4)  NULL,
        BatteryTodayDischargeEnergy  DECIMAL(18,4)  NULL,
        BatteryTotalChargeEnergy     DECIMAL(18,4)  NULL,
        BatteryTotalDischargeEnergy  DECIMAL(18,4)  NULL,
        BatteryType                  DECIMAL(18,4)  NULL,
        BatteryVoltage               DECIMAL(18,4)  NULL,
        BatteryYesterdayChargeEnergy DECIMAL(18,4)  NULL,
        BatteryYesterdayDischargeEnergy DECIMAL(18,4)  NULL,
        BstteryCurrent               DECIMAL(18,4)  NULL,
        BypassAcCurrent              DECIMAL(18,4)  NULL,
        BypassAcVoltage              DECIMAL(18,4)  NULL,
        BypassLoadPower              DECIMAL(18,4)  NULL,
        CurrentDirectionBattery      DECIMAL(18,4)  NULL,
        DcBus                        DECIMAL(18,4)  NULL,
        DcBusHalf                    DECIMAL(18,4)  NULL,
        DcInputType                  DECIMAL(18,4)  NULL,
        EToday                       DECIMAL(18,4)  NULL,
        ETotal                       DECIMAL(18,4)  NULL,
        EpmFailSafe                  DECIMAL(18,4)  NULL,
        Fac                          DECIMAL(18,4)  NULL,
        FamilyLoadPower              DECIMAL(18,4)  NULL,
        GridPurchasedTodayEnergy     DECIMAL(18,4)  NULL,
        GridPurchasedTotalEnergy     DECIMAL(18,4)  NULL,
        GridPurchasedYesterdayEnergy DECIMAL(18,4)  NULL,
        GridSellTodayEnergy          DECIMAL(18,4)  NULL,
        GridSellTotalEnergy          DECIMAL(18,4)  NULL,
        GridSellYesterdayEnergy      DECIMAL(18,4)  NULL,
        HomeLoadTodayEnergy          DECIMAL(18,4)  NULL,
        HomeLoadTotalEnergy          DECIMAL(18,4)  NULL,
        HomeLoadYesterdayEnergy      DECIMAL(18,4)  NULL,
        IAc1                         DECIMAL(18,4)  NULL,
        IAc2                         DECIMAL(18,4)  NULL,
        IAc3                         DECIMAL(18,4)  NULL,
        IPv1                         DECIMAL(18,4)  NULL,
        IPv10                        DECIMAL(18,4)  NULL,
        IPv11                        DECIMAL(18,4)  NULL,
        IPv12                        DECIMAL(18,4)  NULL,
        IPv13                        DECIMAL(18,4)  NULL,
        IPv14                        DECIMAL(18,4)  NULL,
        IPv15                        DECIMAL(18,4)  NULL,
        IPv16                        DECIMAL(18,4)  NULL,
        IPv17                        DECIMAL(18,4)  NULL,
        IPv18                        DECIMAL(18,4)  NULL,
        IPv19                        DECIMAL(18,4)  NULL,
        IPv2                         DECIMAL(18,4)  NULL,
        IPv20                        DECIMAL(18,4)  NULL,
        IPv21                        DECIMAL(18,4)  NULL,
        IPv22                        DECIMAL(18,4)  NULL,
        IPv23                        DECIMAL(18,4)  NULL,
        IPv24                        DECIMAL(18,4)  NULL,
        IPv25                        DECIMAL(18,4)  NULL,
        IPv26                        DECIMAL(18,4)  NULL,
        IPv27                        DECIMAL(18,4)  NULL,
        IPv28                        DECIMAL(18,4)  NULL,
        IPv29                        DECIMAL(18,4)  NULL,
        IPv3                         DECIMAL(18,4)  NULL,
        IPv30                        DECIMAL(18,4)  NULL,
        IPv31                        DECIMAL(18,4)  NULL,
        IPv32                        DECIMAL(18,4)  NULL,
        IPv4                         DECIMAL(18,4)  NULL,
        IPv5                         DECIMAL(18,4)  NULL,
        IPv6                         DECIMAL(18,4)  NULL,
        IPv7                         DECIMAL(18,4)  NULL,
        IPv8                         DECIMAL(18,4)  NULL,
        IPv9                         DECIMAL(18,4)  NULL,
        InverterTemperature          DECIMAL(18,4)  NULL,
        KpiTime                      NVARCHAR(50)  NULL,
        LlcBusVoltage                DECIMAL(18,4)  NULL,
        PSum                         DECIMAL(18,4)  NULL,
        Pac                          DECIMAL(18,4)  NULL,
        PacPec                       NVARCHAR(50)  NULL,
        PacStr                       NVARCHAR(50)  NULL,
        Pepm                         DECIMAL(18,4)  NULL,
        PepmSet                      DECIMAL(18,4)  NULL,
        PfactorLimitSet              DECIMAL(18,4)  NULL,
        PlimitSet                    DECIMAL(18,4)  NULL,
        PowerFactor                  DECIMAL(18,4)  NULL,
        PreactiveLimitSet            DECIMAL(18,4)  NULL,
        SocChargingSet               DECIMAL(18,4)  NULL,
        SocDischargeSet              DECIMAL(18,4)  NULL,
        State                        DECIMAL(18,4)  NULL,
        StorageBatteryCurrent        DECIMAL(18,4)  NULL,
        StorageBatteryVoltage        DECIMAL(18,4)  NULL,
        TimeStr                      NVARCHAR(50)  NULL,
        TimeZone                     DECIMAL(18,4)  NULL,
        UA                           DECIMAL(18,4)  NULL,
        UAc1                         DECIMAL(18,4)  NULL,
        UAc2                         DECIMAL(18,4)  NULL,
        UAc3                         DECIMAL(18,4)  NULL,
        UPv1                         DECIMAL(18,4)  NULL,
        UPv10                        DECIMAL(18,4)  NULL,
        UPv11                        DECIMAL(18,4)  NULL,
        UPv12                        DECIMAL(18,4)  NULL,
        UPv13                        DECIMAL(18,4)  NULL,
        UPv14                        DECIMAL(18,4)  NULL,
        UPv15                        DECIMAL(18,4)  NULL,
        UPv16                        DECIMAL(18,4)  NULL,
        UPv17                        DECIMAL(18,4)  NULL,
        UPv18                        DECIMAL(18,4)  NULL,
        UPv19                        DECIMAL(18,4)  NULL,
        UPv2                         DECIMAL(18,4)  NULL,
        UPv20                        DECIMAL(18,4)  NULL,
        UPv21                        DECIMAL(18,4)  NULL,
        UPv22                        DECIMAL(18,4)  NULL,
        UPv23                        DECIMAL(18,4)  NULL,
        UPv24                        DECIMAL(18,4)  NULL,
        UPv25                        DECIMAL(18,4)  NULL,
        UPv26                        DECIMAL(18,4)  NULL,
        UPv27                        DECIMAL(18,4)  NULL,
        UPv28                        DECIMAL(18,4)  NULL,
        UPv29                        DECIMAL(18,4)  NULL,
        UPv3                         DECIMAL(18,4)  NULL,
        UPv30                        DECIMAL(18,4)  NULL,
        UPv31                        DECIMAL(18,4)  NULL,
        UPv32                        DECIMAL(18,4)  NULL,
        UPv4                         DECIMAL(18,4)  NULL,
        UPv5                         DECIMAL(18,4)  NULL,
        UPv6                         DECIMAL(18,4)  NULL,
        UPv7                         DECIMAL(18,4)  NULL,
        UPv8                         DECIMAL(18,4)  NULL,
        UPv9                         DECIMAL(18,4)  NULL,
        UinitGnd                     DECIMAL(18,4)  NULL,
        KpiDataRaw             NVARCHAR(MAX)  NOT NULL,
        CreationTime           DATETIME2(7)   NOT NULL,
        LastModificationTime   DATETIME2(7)   NULL,
        IsDeleted              BIT            NOT NULL,
        HashDiff               BINARY(32)     NOT NULL,
        FechaCargaInt          DATETIME2(7)   NOT NULL CONSTRAINT DF_Int_factSoliscloudEnergyAndPowerPv_FechaCargaInt DEFAULT (SYSDATETIME()),
        RunId                  INT            NULL
    );
    CREATE INDEX IX_Int_factSoliscloudEnergyAndPowerPv_DeviceId ON [int].factSoliscloudEnergyAndPowerPv (DeviceId);
    CREATE INDEX IX_Int_factSoliscloudEnergyAndPowerPv_Time ON [int].factSoliscloudEnergyAndPowerPv (Time);
END
GO
