-- 088: merge Bronze -> Silver para factSoliscloudEnergyAndPowerPv.
-- INCREMENTAL, mismo patron de watermark (truncado a milisegundo) que los
-- demas facts del dominio Solar. Parsea KpiData (JSON, ~128 claves) a
-- columnas tipadas via JSON_VALUE + TRY_CONVERT.

CREATE OR ALTER PROCEDURE [int].usp_MergeFactSoliscloudEnergyAndPowerPv
    @RunId            INT,
    @UltimoWatermark  DATETIME2(7) = NULL,
    @NuevoWatermark   DATETIME2(7) = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Desde DATETIME2(3) = CONVERT(DATETIME2(3), ISNULL(@UltimoWatermark, '1900-01-01'));

    ;WITH StgIncremental AS (
        SELECT s.*
        FROM stg.factSoliscloudEnergyAndPowerPv s
        WHERE CONVERT(DATETIME2(3), s.CreationTime) > @Desde
           OR CONVERT(DATETIME2(3), s.LastModificationTime) > @Desde
    ),
    StgDeduplicado AS (
        SELECT s.*,
               ROW_NUMBER() OVER (PARTITION BY s.Id ORDER BY (SELECT NULL)) AS rn
        FROM StgIncremental s
    ),
    StgNormalizado AS (
        SELECT
            s.Id,
            RTRIM(s.DeviceId)                                            AS DeviceId,
            DATEADD(SECOND, s.Time / 1000, '1970-01-01')                 AS Time,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.acOutputType')) AS AcOutputType,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryCapacitySoc')) AS BatteryCapacitySoc,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryChargingCurrent')) AS BatteryChargingCurrent,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryDischargeLimiting')) AS BatteryDischargeLimiting,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryHealthSoh')) AS BatteryHealthSoh,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryPower')) AS BatteryPower,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryTodayChargeEnergy')) AS BatteryTodayChargeEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryTodayDischargeEnergy')) AS BatteryTodayDischargeEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryTotalChargeEnergy')) AS BatteryTotalChargeEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryTotalDischargeEnergy')) AS BatteryTotalDischargeEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryType')) AS BatteryType,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryVoltage')) AS BatteryVoltage,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryYesterdayChargeEnergy')) AS BatteryYesterdayChargeEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.batteryYesterdayDischargeEnergy')) AS BatteryYesterdayDischargeEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.bstteryCurrent')) AS BstteryCurrent,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.bypassAcCurrent')) AS BypassAcCurrent,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.bypassAcVoltage')) AS BypassAcVoltage,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.bypassLoadPower')) AS BypassLoadPower,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.currentDirectionBattery')) AS CurrentDirectionBattery,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.dcBus')) AS DcBus,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.dcBusHalf')) AS DcBusHalf,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.dcInputType')) AS DcInputType,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.eToday')) AS EToday,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.eTotal')) AS ETotal,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.epmFailSafe')) AS EpmFailSafe,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.fac')) AS Fac,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.familyLoadPower')) AS FamilyLoadPower,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.gridPurchasedTodayEnergy')) AS GridPurchasedTodayEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.gridPurchasedTotalEnergy')) AS GridPurchasedTotalEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.gridPurchasedYesterdayEnergy')) AS GridPurchasedYesterdayEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.gridSellTodayEnergy')) AS GridSellTodayEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.gridSellTotalEnergy')) AS GridSellTotalEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.gridSellYesterdayEnergy')) AS GridSellYesterdayEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.homeLoadTodayEnergy')) AS HomeLoadTodayEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.homeLoadTotalEnergy')) AS HomeLoadTotalEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.homeLoadYesterdayEnergy')) AS HomeLoadYesterdayEnergy,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iAc1')) AS IAc1,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iAc2')) AS IAc2,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iAc3')) AS IAc3,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv1')) AS IPv1,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv10')) AS IPv10,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv11')) AS IPv11,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv12')) AS IPv12,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv13')) AS IPv13,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv14')) AS IPv14,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv15')) AS IPv15,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv16')) AS IPv16,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv17')) AS IPv17,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv18')) AS IPv18,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv19')) AS IPv19,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv2')) AS IPv2,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv20')) AS IPv20,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv21')) AS IPv21,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv22')) AS IPv22,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv23')) AS IPv23,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv24')) AS IPv24,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv25')) AS IPv25,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv26')) AS IPv26,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv27')) AS IPv27,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv28')) AS IPv28,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv29')) AS IPv29,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv3')) AS IPv3,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv30')) AS IPv30,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv31')) AS IPv31,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv32')) AS IPv32,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv4')) AS IPv4,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv5')) AS IPv5,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv6')) AS IPv6,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv7')) AS IPv7,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv8')) AS IPv8,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.iPv9')) AS IPv9,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.inverterTemperature')) AS InverterTemperature,
            JSON_VALUE(s.KpiData, '$.time') AS KpiTime,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.llcBusVoltage')) AS LlcBusVoltage,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.pSum')) AS PSum,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.pac')) AS Pac,
            JSON_VALUE(s.KpiData, '$.pacPec') AS PacPec,
            JSON_VALUE(s.KpiData, '$.pacStr') AS PacStr,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.pepm')) AS Pepm,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.pepmSet')) AS PepmSet,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.pfactorLimitSet')) AS PfactorLimitSet,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.plimitSet')) AS PlimitSet,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.powerFactor')) AS PowerFactor,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.preactiveLimitSet')) AS PreactiveLimitSet,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.socChargingSet')) AS SocChargingSet,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.socDischargeSet')) AS SocDischargeSet,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.state')) AS State,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.storageBatteryCurrent')) AS StorageBatteryCurrent,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.storageBatteryVoltage')) AS StorageBatteryVoltage,
            JSON_VALUE(s.KpiData, '$.timeStr') AS TimeStr,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.timeZone')) AS TimeZone,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uA')) AS UA,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uAc1')) AS UAc1,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uAc2')) AS UAc2,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uAc3')) AS UAc3,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv1')) AS UPv1,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv10')) AS UPv10,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv11')) AS UPv11,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv12')) AS UPv12,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv13')) AS UPv13,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv14')) AS UPv14,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv15')) AS UPv15,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv16')) AS UPv16,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv17')) AS UPv17,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv18')) AS UPv18,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv19')) AS UPv19,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv2')) AS UPv2,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv20')) AS UPv20,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv21')) AS UPv21,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv22')) AS UPv22,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv23')) AS UPv23,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv24')) AS UPv24,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv25')) AS UPv25,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv26')) AS UPv26,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv27')) AS UPv27,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv28')) AS UPv28,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv29')) AS UPv29,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv3')) AS UPv3,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv30')) AS UPv30,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv31')) AS UPv31,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv32')) AS UPv32,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv4')) AS UPv4,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv5')) AS UPv5,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv6')) AS UPv6,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv7')) AS UPv7,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv8')) AS UPv8,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uPv9')) AS UPv9,
            TRY_CONVERT(DECIMAL(18,4), JSON_VALUE(s.KpiData, '$.uinitGnd')) AS UinitGnd,
            s.KpiData                                                    AS KpiDataRaw,
            s.CreationTime,
            s.LastModificationTime,
            s.IsDeleted
        FROM StgDeduplicado s
        WHERE s.rn = 1
    ),
    StgConHash AS (
        SELECT
            n.*,
            HASHBYTES('SHA2_256', (SELECT n.* FOR XML RAW, BINARY BASE64)) AS HashDiff
        FROM StgNormalizado n
    )
    SELECT * INTO #Origen FROM StgConHash;

    DECLARE @FilasLeidas INT = (SELECT COUNT(*) FROM #Origen);

    CREATE TABLE #AccionesMerge (Accion VARCHAR(20) NOT NULL);

    MERGE [int].factSoliscloudEnergyAndPowerPv AS destino
        USING #Origen AS origen
        ON destino.Id = origen.Id
    WHEN MATCHED AND destino.HashDiff <> origen.HashDiff THEN
        UPDATE SET
            DeviceId               = origen.DeviceId,
            Time                    = origen.Time,
            AcOutputType                 = origen.AcOutputType,
            BatteryCapacitySoc           = origen.BatteryCapacitySoc,
            BatteryChargingCurrent       = origen.BatteryChargingCurrent,
            BatteryDischargeLimiting     = origen.BatteryDischargeLimiting,
            BatteryHealthSoh             = origen.BatteryHealthSoh,
            BatteryPower                 = origen.BatteryPower,
            BatteryTodayChargeEnergy     = origen.BatteryTodayChargeEnergy,
            BatteryTodayDischargeEnergy  = origen.BatteryTodayDischargeEnergy,
            BatteryTotalChargeEnergy     = origen.BatteryTotalChargeEnergy,
            BatteryTotalDischargeEnergy  = origen.BatteryTotalDischargeEnergy,
            BatteryType                  = origen.BatteryType,
            BatteryVoltage               = origen.BatteryVoltage,
            BatteryYesterdayChargeEnergy = origen.BatteryYesterdayChargeEnergy,
            BatteryYesterdayDischargeEnergy = origen.BatteryYesterdayDischargeEnergy,
            BstteryCurrent               = origen.BstteryCurrent,
            BypassAcCurrent              = origen.BypassAcCurrent,
            BypassAcVoltage              = origen.BypassAcVoltage,
            BypassLoadPower              = origen.BypassLoadPower,
            CurrentDirectionBattery      = origen.CurrentDirectionBattery,
            DcBus                        = origen.DcBus,
            DcBusHalf                    = origen.DcBusHalf,
            DcInputType                  = origen.DcInputType,
            EToday                       = origen.EToday,
            ETotal                       = origen.ETotal,
            EpmFailSafe                  = origen.EpmFailSafe,
            Fac                          = origen.Fac,
            FamilyLoadPower              = origen.FamilyLoadPower,
            GridPurchasedTodayEnergy     = origen.GridPurchasedTodayEnergy,
            GridPurchasedTotalEnergy     = origen.GridPurchasedTotalEnergy,
            GridPurchasedYesterdayEnergy = origen.GridPurchasedYesterdayEnergy,
            GridSellTodayEnergy          = origen.GridSellTodayEnergy,
            GridSellTotalEnergy          = origen.GridSellTotalEnergy,
            GridSellYesterdayEnergy      = origen.GridSellYesterdayEnergy,
            HomeLoadTodayEnergy          = origen.HomeLoadTodayEnergy,
            HomeLoadTotalEnergy          = origen.HomeLoadTotalEnergy,
            HomeLoadYesterdayEnergy      = origen.HomeLoadYesterdayEnergy,
            IAc1                         = origen.IAc1,
            IAc2                         = origen.IAc2,
            IAc3                         = origen.IAc3,
            IPv1                         = origen.IPv1,
            IPv10                        = origen.IPv10,
            IPv11                        = origen.IPv11,
            IPv12                        = origen.IPv12,
            IPv13                        = origen.IPv13,
            IPv14                        = origen.IPv14,
            IPv15                        = origen.IPv15,
            IPv16                        = origen.IPv16,
            IPv17                        = origen.IPv17,
            IPv18                        = origen.IPv18,
            IPv19                        = origen.IPv19,
            IPv2                         = origen.IPv2,
            IPv20                        = origen.IPv20,
            IPv21                        = origen.IPv21,
            IPv22                        = origen.IPv22,
            IPv23                        = origen.IPv23,
            IPv24                        = origen.IPv24,
            IPv25                        = origen.IPv25,
            IPv26                        = origen.IPv26,
            IPv27                        = origen.IPv27,
            IPv28                        = origen.IPv28,
            IPv29                        = origen.IPv29,
            IPv3                         = origen.IPv3,
            IPv30                        = origen.IPv30,
            IPv31                        = origen.IPv31,
            IPv32                        = origen.IPv32,
            IPv4                         = origen.IPv4,
            IPv5                         = origen.IPv5,
            IPv6                         = origen.IPv6,
            IPv7                         = origen.IPv7,
            IPv8                         = origen.IPv8,
            IPv9                         = origen.IPv9,
            InverterTemperature          = origen.InverterTemperature,
            KpiTime                      = origen.KpiTime,
            LlcBusVoltage                = origen.LlcBusVoltage,
            PSum                         = origen.PSum,
            Pac                          = origen.Pac,
            PacPec                       = origen.PacPec,
            PacStr                       = origen.PacStr,
            Pepm                         = origen.Pepm,
            PepmSet                      = origen.PepmSet,
            PfactorLimitSet              = origen.PfactorLimitSet,
            PlimitSet                    = origen.PlimitSet,
            PowerFactor                  = origen.PowerFactor,
            PreactiveLimitSet            = origen.PreactiveLimitSet,
            SocChargingSet               = origen.SocChargingSet,
            SocDischargeSet              = origen.SocDischargeSet,
            State                        = origen.State,
            StorageBatteryCurrent        = origen.StorageBatteryCurrent,
            StorageBatteryVoltage        = origen.StorageBatteryVoltage,
            TimeStr                      = origen.TimeStr,
            TimeZone                     = origen.TimeZone,
            UA                           = origen.UA,
            UAc1                         = origen.UAc1,
            UAc2                         = origen.UAc2,
            UAc3                         = origen.UAc3,
            UPv1                         = origen.UPv1,
            UPv10                        = origen.UPv10,
            UPv11                        = origen.UPv11,
            UPv12                        = origen.UPv12,
            UPv13                        = origen.UPv13,
            UPv14                        = origen.UPv14,
            UPv15                        = origen.UPv15,
            UPv16                        = origen.UPv16,
            UPv17                        = origen.UPv17,
            UPv18                        = origen.UPv18,
            UPv19                        = origen.UPv19,
            UPv2                         = origen.UPv2,
            UPv20                        = origen.UPv20,
            UPv21                        = origen.UPv21,
            UPv22                        = origen.UPv22,
            UPv23                        = origen.UPv23,
            UPv24                        = origen.UPv24,
            UPv25                        = origen.UPv25,
            UPv26                        = origen.UPv26,
            UPv27                        = origen.UPv27,
            UPv28                        = origen.UPv28,
            UPv29                        = origen.UPv29,
            UPv3                         = origen.UPv3,
            UPv30                        = origen.UPv30,
            UPv31                        = origen.UPv31,
            UPv32                        = origen.UPv32,
            UPv4                         = origen.UPv4,
            UPv5                         = origen.UPv5,
            UPv6                         = origen.UPv6,
            UPv7                         = origen.UPv7,
            UPv8                         = origen.UPv8,
            UPv9                         = origen.UPv9,
            UinitGnd                     = origen.UinitGnd,
            KpiDataRaw              = origen.KpiDataRaw,
            CreationTime            = origen.CreationTime,
            LastModificationTime    = origen.LastModificationTime,
            IsDeleted               = origen.IsDeleted,
            HashDiff                = origen.HashDiff,
            FechaCargaInt           = SYSDATETIME(),
            RunId                   = @RunId
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            Id, DeviceId, Time,
            AcOutputType, BatteryCapacitySoc, BatteryChargingCurrent, BatteryDischargeLimiting, BatteryHealthSoh, BatteryPower,
            BatteryTodayChargeEnergy, BatteryTodayDischargeEnergy, BatteryTotalChargeEnergy, BatteryTotalDischargeEnergy, BatteryType, BatteryVoltage,
            BatteryYesterdayChargeEnergy, BatteryYesterdayDischargeEnergy, BstteryCurrent, BypassAcCurrent, BypassAcVoltage, BypassLoadPower,
            CurrentDirectionBattery, DcBus, DcBusHalf, DcInputType, EToday, ETotal,
            EpmFailSafe, Fac, FamilyLoadPower, GridPurchasedTodayEnergy, GridPurchasedTotalEnergy, GridPurchasedYesterdayEnergy,
            GridSellTodayEnergy, GridSellTotalEnergy, GridSellYesterdayEnergy, HomeLoadTodayEnergy, HomeLoadTotalEnergy, HomeLoadYesterdayEnergy,
            IAc1, IAc2, IAc3, IPv1, IPv10, IPv11,
            IPv12, IPv13, IPv14, IPv15, IPv16, IPv17,
            IPv18, IPv19, IPv2, IPv20, IPv21, IPv22,
            IPv23, IPv24, IPv25, IPv26, IPv27, IPv28,
            IPv29, IPv3, IPv30, IPv31, IPv32, IPv4,
            IPv5, IPv6, IPv7, IPv8, IPv9, InverterTemperature,
            KpiTime, LlcBusVoltage, PSum, Pac, PacPec, PacStr,
            Pepm, PepmSet, PfactorLimitSet, PlimitSet, PowerFactor, PreactiveLimitSet,
            SocChargingSet, SocDischargeSet, State, StorageBatteryCurrent, StorageBatteryVoltage, TimeStr,
            TimeZone, UA, UAc1, UAc2, UAc3, UPv1,
            UPv10, UPv11, UPv12, UPv13, UPv14, UPv15,
            UPv16, UPv17, UPv18, UPv19, UPv2, UPv20,
            UPv21, UPv22, UPv23, UPv24, UPv25, UPv26,
            UPv27, UPv28, UPv29, UPv3, UPv30, UPv31,
            UPv32, UPv4, UPv5, UPv6, UPv7, UPv8,
            UPv9, UinitGnd,
            KpiDataRaw, CreationTime, LastModificationTime, IsDeleted, HashDiff, RunId
        )
        VALUES (
            origen.Id, origen.DeviceId, origen.Time,
            origen.AcOutputType, origen.BatteryCapacitySoc, origen.BatteryChargingCurrent, origen.BatteryDischargeLimiting, origen.BatteryHealthSoh, origen.BatteryPower,
            origen.BatteryTodayChargeEnergy, origen.BatteryTodayDischargeEnergy, origen.BatteryTotalChargeEnergy, origen.BatteryTotalDischargeEnergy, origen.BatteryType, origen.BatteryVoltage,
            origen.BatteryYesterdayChargeEnergy, origen.BatteryYesterdayDischargeEnergy, origen.BstteryCurrent, origen.BypassAcCurrent, origen.BypassAcVoltage, origen.BypassLoadPower,
            origen.CurrentDirectionBattery, origen.DcBus, origen.DcBusHalf, origen.DcInputType, origen.EToday, origen.ETotal,
            origen.EpmFailSafe, origen.Fac, origen.FamilyLoadPower, origen.GridPurchasedTodayEnergy, origen.GridPurchasedTotalEnergy, origen.GridPurchasedYesterdayEnergy,
            origen.GridSellTodayEnergy, origen.GridSellTotalEnergy, origen.GridSellYesterdayEnergy, origen.HomeLoadTodayEnergy, origen.HomeLoadTotalEnergy, origen.HomeLoadYesterdayEnergy,
            origen.IAc1, origen.IAc2, origen.IAc3, origen.IPv1, origen.IPv10, origen.IPv11,
            origen.IPv12, origen.IPv13, origen.IPv14, origen.IPv15, origen.IPv16, origen.IPv17,
            origen.IPv18, origen.IPv19, origen.IPv2, origen.IPv20, origen.IPv21, origen.IPv22,
            origen.IPv23, origen.IPv24, origen.IPv25, origen.IPv26, origen.IPv27, origen.IPv28,
            origen.IPv29, origen.IPv3, origen.IPv30, origen.IPv31, origen.IPv32, origen.IPv4,
            origen.IPv5, origen.IPv6, origen.IPv7, origen.IPv8, origen.IPv9, origen.InverterTemperature,
            origen.KpiTime, origen.LlcBusVoltage, origen.PSum, origen.Pac, origen.PacPec, origen.PacStr,
            origen.Pepm, origen.PepmSet, origen.PfactorLimitSet, origen.PlimitSet, origen.PowerFactor, origen.PreactiveLimitSet,
            origen.SocChargingSet, origen.SocDischargeSet, origen.State, origen.StorageBatteryCurrent, origen.StorageBatteryVoltage, origen.TimeStr,
            origen.TimeZone, origen.UA, origen.UAc1, origen.UAc2, origen.UAc3, origen.UPv1,
            origen.UPv10, origen.UPv11, origen.UPv12, origen.UPv13, origen.UPv14, origen.UPv15,
            origen.UPv16, origen.UPv17, origen.UPv18, origen.UPv19, origen.UPv2, origen.UPv20,
            origen.UPv21, origen.UPv22, origen.UPv23, origen.UPv24, origen.UPv25, origen.UPv26,
            origen.UPv27, origen.UPv28, origen.UPv29, origen.UPv3, origen.UPv30, origen.UPv31,
            origen.UPv32, origen.UPv4, origen.UPv5, origen.UPv6, origen.UPv7, origen.UPv8,
            origen.UPv9, origen.UinitGnd,
            origen.KpiDataRaw, origen.CreationTime, origen.LastModificationTime,
            origen.IsDeleted, origen.HashDiff, @RunId
        )
    OUTPUT $action INTO #AccionesMerge;

    SELECT @NuevoWatermark = CONVERT(DATETIME2(3), MAX(v.Marca))
    FROM (
        SELECT CreationTime AS Marca FROM #Origen
        UNION ALL
        SELECT LastModificationTime FROM #Origen WHERE LastModificationTime IS NOT NULL
    ) v;
    SET @NuevoWatermark = ISNULL(@NuevoWatermark, @Desde);

    SELECT
        @FilasLeidas                                                                 AS FilasLeidas,
        ISNULL(SUM(CASE WHEN Accion = 'INSERT' THEN 1 ELSE 0 END), 0)                AS FilasInsertadas,
        ISNULL(SUM(CASE WHEN Accion = 'UPDATE' THEN 1 ELSE 0 END), 0)                AS FilasActualizadas,
        @FilasLeidas - ISNULL(SUM(CASE WHEN Accion = 'INSERT' THEN 1 ELSE 0 END), 0)
                      - ISNULL(SUM(CASE WHEN Accion = 'UPDATE' THEN 1 ELSE 0 END), 0) AS FilasIgnoradas,
        @NuevoWatermark                                                              AS NuevoWatermark
    FROM #AccionesMerge;

    DROP TABLE #Origen;
END
GO
