-- 091: corrige la resolucion de SoliscloudDeviceKey en
-- dw.usp_MergeFactSoliscloudEnergyAndPowerPv. El campo "DeviceId" de este
-- fact (viene del endpoint de telemetria de Soliscloud) en realidad
-- contiene el numero de serie del inversor -- coincide con
-- dw.dimSoliscloudDevices.DeviceSn, NO con dw.dimSoliscloudDevices.DeviceId
-- (que es un id interno distinto de la API "device list"). Confirmado
-- contra datos reales: las 16107 filas cargadas inicialmente quedaron con
-- SoliscloudDeviceKey NULL por este join incorrecto. Se corrige el JOIN y
-- se amplia la condicion de MATCHED para que tambien actualice filas ya
-- cargadas cuyo SoliscloudDeviceKey siga NULL (sin esto, el merge no las
-- tocaria de nuevo porque su HashDiff de Silver no cambio).

CREATE OR ALTER PROCEDURE dw.usp_MergeFactSoliscloudEnergyAndPowerPv
    @RunId            INT,
    @UltimoWatermark  DATETIME2(7) = NULL,
    @NuevoWatermark   DATETIME2(7) = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Desde DATETIME2(3) = CONVERT(DATETIME2(3), ISNULL(@UltimoWatermark, '1900-01-01'));

    ;WITH Origen AS (
        SELECT
            f.Id,
            d.SoliscloudDeviceKey,
            f.DeviceId,
            f.Time,
            f.AcOutputType,
            f.BatteryCapacitySoc,
            f.BatteryChargingCurrent,
            f.BatteryDischargeLimiting,
            f.BatteryHealthSoh,
            f.BatteryPower,
            f.BatteryTodayChargeEnergy,
            f.BatteryTodayDischargeEnergy,
            f.BatteryTotalChargeEnergy,
            f.BatteryTotalDischargeEnergy,
            f.BatteryType,
            f.BatteryVoltage,
            f.BatteryYesterdayChargeEnergy,
            f.BatteryYesterdayDischargeEnergy,
            f.BstteryCurrent,
            f.BypassAcCurrent,
            f.BypassAcVoltage,
            f.BypassLoadPower,
            f.CurrentDirectionBattery,
            f.DcBus,
            f.DcBusHalf,
            f.DcInputType,
            f.EToday,
            f.ETotal,
            f.EpmFailSafe,
            f.Fac,
            f.FamilyLoadPower,
            f.GridPurchasedTodayEnergy,
            f.GridPurchasedTotalEnergy,
            f.GridPurchasedYesterdayEnergy,
            f.GridSellTodayEnergy,
            f.GridSellTotalEnergy,
            f.GridSellYesterdayEnergy,
            f.HomeLoadTodayEnergy,
            f.HomeLoadTotalEnergy,
            f.HomeLoadYesterdayEnergy,
            f.IAc1,
            f.IAc2,
            f.IAc3,
            f.IPv1,
            f.IPv10,
            f.IPv11,
            f.IPv12,
            f.IPv13,
            f.IPv14,
            f.IPv15,
            f.IPv16,
            f.IPv17,
            f.IPv18,
            f.IPv19,
            f.IPv2,
            f.IPv20,
            f.IPv21,
            f.IPv22,
            f.IPv23,
            f.IPv24,
            f.IPv25,
            f.IPv26,
            f.IPv27,
            f.IPv28,
            f.IPv29,
            f.IPv3,
            f.IPv30,
            f.IPv31,
            f.IPv32,
            f.IPv4,
            f.IPv5,
            f.IPv6,
            f.IPv7,
            f.IPv8,
            f.IPv9,
            f.InverterTemperature,
            f.KpiTime,
            f.LlcBusVoltage,
            f.PSum,
            f.Pac,
            f.PacPec,
            f.PacStr,
            f.Pepm,
            f.PepmSet,
            f.PfactorLimitSet,
            f.PlimitSet,
            f.PowerFactor,
            f.PreactiveLimitSet,
            f.SocChargingSet,
            f.SocDischargeSet,
            f.State,
            f.StorageBatteryCurrent,
            f.StorageBatteryVoltage,
            f.TimeStr,
            f.TimeZone,
            f.UA,
            f.UAc1,
            f.UAc2,
            f.UAc3,
            f.UPv1,
            f.UPv10,
            f.UPv11,
            f.UPv12,
            f.UPv13,
            f.UPv14,
            f.UPv15,
            f.UPv16,
            f.UPv17,
            f.UPv18,
            f.UPv19,
            f.UPv2,
            f.UPv20,
            f.UPv21,
            f.UPv22,
            f.UPv23,
            f.UPv24,
            f.UPv25,
            f.UPv26,
            f.UPv27,
            f.UPv28,
            f.UPv29,
            f.UPv3,
            f.UPv30,
            f.UPv31,
            f.UPv32,
            f.UPv4,
            f.UPv5,
            f.UPv6,
            f.UPv7,
            f.UPv8,
            f.UPv9,
            f.UinitGnd,
            f.CreationTime,
            f.LastModificationTime,
            f.IsDeleted,
            f.HashDiff,
            f.FechaCargaInt
        FROM [int].factSoliscloudEnergyAndPowerPv f
        LEFT JOIN dw.dimSoliscloudDevices d ON d.DeviceSn = f.DeviceId
        WHERE CONVERT(DATETIME2(3), f.FechaCargaInt) > @Desde AND f.IsDeleted = 0
    )
    SELECT * INTO #Origen FROM Origen;

    DECLARE @FilasLeidas INT = (SELECT COUNT(*) FROM #Origen);

    CREATE TABLE #AccionesMerge (Accion VARCHAR(20) NOT NULL);

    MERGE dw.factSoliscloudEnergyAndPowerPv AS destino
        USING #Origen AS origen
        ON destino.Id = origen.Id
    WHEN MATCHED AND (destino.HashDiff <> origen.HashDiff OR (destino.SoliscloudDeviceKey IS NULL AND origen.SoliscloudDeviceKey IS NOT NULL)) THEN
        UPDATE SET
            SoliscloudDeviceKey   = origen.SoliscloudDeviceKey,
            DeviceId              = origen.DeviceId,
            Time                  = origen.Time,
            AcOutputType                 = origen.AcOutputType,
            BatteryCapacitySoc           = origen.BatteryCapacitySoc,
            BatteryChargingCurrent       = origen.BatteryChargingCurrent,
            BatteryDischargeLimiting     = origen.BatteryDischargeLimiting,
            BatteryHealthSoh             = origen.BatteryHealthSoh,
            BatteryPower                 = origen.BatteryPower,
            BatteryTodayChargeEnergy     = origen.BatteryTodayChargeEnergy,
            BatteryTodayDischargeEnergy  = origen.BatteryTodayDischargeEnergy,
            BatteryTotalChargeEnergy     = origen.BatteryTotalChargeEnergy,
            BatteryTotalDischargeEnergy  = origen.BatteryTotalDischargeEnergy,
            BatteryType                  = origen.BatteryType,
            BatteryVoltage               = origen.BatteryVoltage,
            BatteryYesterdayChargeEnergy = origen.BatteryYesterdayChargeEnergy,
            BatteryYesterdayDischargeEnergy = origen.BatteryYesterdayDischargeEnergy,
            BstteryCurrent               = origen.BstteryCurrent,
            BypassAcCurrent              = origen.BypassAcCurrent,
            BypassAcVoltage              = origen.BypassAcVoltage,
            BypassLoadPower              = origen.BypassLoadPower,
            CurrentDirectionBattery      = origen.CurrentDirectionBattery,
            DcBus                        = origen.DcBus,
            DcBusHalf                    = origen.DcBusHalf,
            DcInputType                  = origen.DcInputType,
            EToday                       = origen.EToday,
            ETotal                       = origen.ETotal,
            EpmFailSafe                  = origen.EpmFailSafe,
            Fac                          = origen.Fac,
            FamilyLoadPower              = origen.FamilyLoadPower,
            GridPurchasedTodayEnergy     = origen.GridPurchasedTodayEnergy,
            GridPurchasedTotalEnergy     = origen.GridPurchasedTotalEnergy,
            GridPurchasedYesterdayEnergy = origen.GridPurchasedYesterdayEnergy,
            GridSellTodayEnergy          = origen.GridSellTodayEnergy,
            GridSellTotalEnergy          = origen.GridSellTotalEnergy,
            GridSellYesterdayEnergy      = origen.GridSellYesterdayEnergy,
            HomeLoadTodayEnergy          = origen.HomeLoadTodayEnergy,
            HomeLoadTotalEnergy          = origen.HomeLoadTotalEnergy,
            HomeLoadYesterdayEnergy      = origen.HomeLoadYesterdayEnergy,
            IAc1                         = origen.IAc1,
            IAc2                         = origen.IAc2,
            IAc3                         = origen.IAc3,
            IPv1                         = origen.IPv1,
            IPv10                        = origen.IPv10,
            IPv11                        = origen.IPv11,
            IPv12                        = origen.IPv12,
            IPv13                        = origen.IPv13,
            IPv14                        = origen.IPv14,
            IPv15                        = origen.IPv15,
            IPv16                        = origen.IPv16,
            IPv17                        = origen.IPv17,
            IPv18                        = origen.IPv18,
            IPv19                        = origen.IPv19,
            IPv2                         = origen.IPv2,
            IPv20                        = origen.IPv20,
            IPv21                        = origen.IPv21,
            IPv22                        = origen.IPv22,
            IPv23                        = origen.IPv23,
            IPv24                        = origen.IPv24,
            IPv25                        = origen.IPv25,
            IPv26                        = origen.IPv26,
            IPv27                        = origen.IPv27,
            IPv28                        = origen.IPv28,
            IPv29                        = origen.IPv29,
            IPv3                         = origen.IPv3,
            IPv30                        = origen.IPv30,
            IPv31                        = origen.IPv31,
            IPv32                        = origen.IPv32,
            IPv4                         = origen.IPv4,
            IPv5                         = origen.IPv5,
            IPv6                         = origen.IPv6,
            IPv7                         = origen.IPv7,
            IPv8                         = origen.IPv8,
            IPv9                         = origen.IPv9,
            InverterTemperature          = origen.InverterTemperature,
            KpiTime                      = origen.KpiTime,
            LlcBusVoltage                = origen.LlcBusVoltage,
            PSum                         = origen.PSum,
            Pac                          = origen.Pac,
            PacPec                       = origen.PacPec,
            PacStr                       = origen.PacStr,
            Pepm                         = origen.Pepm,
            PepmSet                      = origen.PepmSet,
            PfactorLimitSet              = origen.PfactorLimitSet,
            PlimitSet                    = origen.PlimitSet,
            PowerFactor                  = origen.PowerFactor,
            PreactiveLimitSet            = origen.PreactiveLimitSet,
            SocChargingSet               = origen.SocChargingSet,
            SocDischargeSet              = origen.SocDischargeSet,
            State                        = origen.State,
            StorageBatteryCurrent        = origen.StorageBatteryCurrent,
            StorageBatteryVoltage        = origen.StorageBatteryVoltage,
            TimeStr                      = origen.TimeStr,
            TimeZone                     = origen.TimeZone,
            UA                           = origen.UA,
            UAc1                         = origen.UAc1,
            UAc2                         = origen.UAc2,
            UAc3                         = origen.UAc3,
            UPv1                         = origen.UPv1,
            UPv10                        = origen.UPv10,
            UPv11                        = origen.UPv11,
            UPv12                        = origen.UPv12,
            UPv13                        = origen.UPv13,
            UPv14                        = origen.UPv14,
            UPv15                        = origen.UPv15,
            UPv16                        = origen.UPv16,
            UPv17                        = origen.UPv17,
            UPv18                        = origen.UPv18,
            UPv19                        = origen.UPv19,
            UPv2                         = origen.UPv2,
            UPv20                        = origen.UPv20,
            UPv21                        = origen.UPv21,
            UPv22                        = origen.UPv22,
            UPv23                        = origen.UPv23,
            UPv24                        = origen.UPv24,
            UPv25                        = origen.UPv25,
            UPv26                        = origen.UPv26,
            UPv27                        = origen.UPv27,
            UPv28                        = origen.UPv28,
            UPv29                        = origen.UPv29,
            UPv3                         = origen.UPv3,
            UPv30                        = origen.UPv30,
            UPv31                        = origen.UPv31,
            UPv32                        = origen.UPv32,
            UPv4                         = origen.UPv4,
            UPv5                         = origen.UPv5,
            UPv6                         = origen.UPv6,
            UPv7                         = origen.UPv7,
            UPv8                         = origen.UPv8,
            UPv9                         = origen.UPv9,
            UinitGnd                     = origen.UinitGnd,
            CreationTime          = origen.CreationTime,
            LastModificationTime  = origen.LastModificationTime,
            IsDeleted             = origen.IsDeleted,
            HashDiff              = origen.HashDiff,
            FechaCargaDw          = SYSDATETIME(),
            RunId                 = @RunId
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            Id, SoliscloudDeviceKey, DeviceId, Time,
            AcOutputType, BatteryCapacitySoc, BatteryChargingCurrent, BatteryDischargeLimiting, BatteryHealthSoh, BatteryPower,
            BatteryTodayChargeEnergy, BatteryTodayDischargeEnergy, BatteryTotalChargeEnergy, BatteryTotalDischargeEnergy, BatteryType, BatteryVoltage,
            BatteryYesterdayChargeEnergy, BatteryYesterdayDischargeEnergy, BstteryCurrent, BypassAcCurrent, BypassAcVoltage, BypassLoadPower,
            CurrentDirectionBattery, DcBus, DcBusHalf, DcInputType, EToday, ETotal,
            EpmFailSafe, Fac, FamilyLoadPower, GridPurchasedTodayEnergy, GridPurchasedTotalEnergy, GridPurchasedYesterdayEnergy,
            GridSellTodayEnergy, GridSellTotalEnergy, GridSellYesterdayEnergy, HomeLoadTodayEnergy, HomeLoadTotalEnergy, HomeLoadYesterdayEnergy,
            IAc1, IAc2, IAc3, IPv1, IPv10, IPv11,
            IPv12, IPv13, IPv14, IPv15, IPv16, IPv17,
            IPv18, IPv19, IPv2, IPv20, IPv21, IPv22,
            IPv23, IPv24, IPv25, IPv26, IPv27, IPv28,
            IPv29, IPv3, IPv30, IPv31, IPv32, IPv4,
            IPv5, IPv6, IPv7, IPv8, IPv9, InverterTemperature,
            KpiTime, LlcBusVoltage, PSum, Pac, PacPec, PacStr,
            Pepm, PepmSet, PfactorLimitSet, PlimitSet, PowerFactor, PreactiveLimitSet,
            SocChargingSet, SocDischargeSet, State, StorageBatteryCurrent, StorageBatteryVoltage, TimeStr,
            TimeZone, UA, UAc1, UAc2, UAc3, UPv1,
            UPv10, UPv11, UPv12, UPv13, UPv14, UPv15,
            UPv16, UPv17, UPv18, UPv19, UPv2, UPv20,
            UPv21, UPv22, UPv23, UPv24, UPv25, UPv26,
            UPv27, UPv28, UPv29, UPv3, UPv30, UPv31,
            UPv32, UPv4, UPv5, UPv6, UPv7, UPv8,
            UPv9, UinitGnd,
            CreationTime, LastModificationTime, IsDeleted, HashDiff, RunId
        )
        VALUES (
            origen.Id, origen.SoliscloudDeviceKey, origen.DeviceId, origen.Time,
            origen.AcOutputType, origen.BatteryCapacitySoc, origen.BatteryChargingCurrent, origen.BatteryDischargeLimiting, origen.BatteryHealthSoh, origen.BatteryPower,
            origen.BatteryTodayChargeEnergy, origen.BatteryTodayDischargeEnergy, origen.BatteryTotalChargeEnergy, origen.BatteryTotalDischargeEnergy, origen.BatteryType, origen.BatteryVoltage,
            origen.BatteryYesterdayChargeEnergy, origen.BatteryYesterdayDischargeEnergy, origen.BstteryCurrent, origen.BypassAcCurrent, origen.BypassAcVoltage, origen.BypassLoadPower,
            origen.CurrentDirectionBattery, origen.DcBus, origen.DcBusHalf, origen.DcInputType, origen.EToday, origen.ETotal,
            origen.EpmFailSafe, origen.Fac, origen.FamilyLoadPower, origen.GridPurchasedTodayEnergy, origen.GridPurchasedTotalEnergy, origen.GridPurchasedYesterdayEnergy,
            origen.GridSellTodayEnergy, origen.GridSellTotalEnergy, origen.GridSellYesterdayEnergy, origen.HomeLoadTodayEnergy, origen.HomeLoadTotalEnergy, origen.HomeLoadYesterdayEnergy,
            origen.IAc1, origen.IAc2, origen.IAc3, origen.IPv1, origen.IPv10, origen.IPv11,
            origen.IPv12, origen.IPv13, origen.IPv14, origen.IPv15, origen.IPv16, origen.IPv17,
            origen.IPv18, origen.IPv19, origen.IPv2, origen.IPv20, origen.IPv21, origen.IPv22,
            origen.IPv23, origen.IPv24, origen.IPv25, origen.IPv26, origen.IPv27, origen.IPv28,
            origen.IPv29, origen.IPv3, origen.IPv30, origen.IPv31, origen.IPv32, origen.IPv4,
            origen.IPv5, origen.IPv6, origen.IPv7, origen.IPv8, origen.IPv9, origen.InverterTemperature,
            origen.KpiTime, origen.LlcBusVoltage, origen.PSum, origen.Pac, origen.PacPec, origen.PacStr,
            origen.Pepm, origen.PepmSet, origen.PfactorLimitSet, origen.PlimitSet, origen.PowerFactor, origen.PreactiveLimitSet,
            origen.SocChargingSet, origen.SocDischargeSet, origen.State, origen.StorageBatteryCurrent, origen.StorageBatteryVoltage, origen.TimeStr,
            origen.TimeZone, origen.UA, origen.UAc1, origen.UAc2, origen.UAc3, origen.UPv1,
            origen.UPv10, origen.UPv11, origen.UPv12, origen.UPv13, origen.UPv14, origen.UPv15,
            origen.UPv16, origen.UPv17, origen.UPv18, origen.UPv19, origen.UPv2, origen.UPv20,
            origen.UPv21, origen.UPv22, origen.UPv23, origen.UPv24, origen.UPv25, origen.UPv26,
            origen.UPv27, origen.UPv28, origen.UPv29, origen.UPv3, origen.UPv30, origen.UPv31,
            origen.UPv32, origen.UPv4, origen.UPv5, origen.UPv6, origen.UPv7, origen.UPv8,
            origen.UPv9, origen.UinitGnd,
            origen.CreationTime, origen.LastModificationTime, origen.IsDeleted, origen.HashDiff, @RunId
        )
    OUTPUT $action INTO #AccionesMerge;

    SELECT @NuevoWatermark = CONVERT(DATETIME2(3), MAX(FechaCargaInt)) FROM #Origen;
    SET @NuevoWatermark = ISNULL(@NuevoWatermark, @Desde);

    SELECT
        @FilasLeidas                                                                 AS FilasLeidas,
        ISNULL(SUM(CASE WHEN Accion = 'INSERT' THEN 1 ELSE 0 END), 0)                AS FilasInsertadas,
        ISNULL(SUM(CASE WHEN Accion = 'UPDATE' THEN 1 ELSE 0 END), 0)                AS FilasActualizadas,
        @FilasLeidas - ISNULL(SUM(CASE WHEN Accion = 'INSERT' THEN 1 ELSE 0 END), 0)
                      - ISNULL(SUM(CASE WHEN Accion = 'UPDATE' THEN 1 ELSE 0 END), 0) AS FilasIgnoradas,
        @NuevoWatermark                                                              AS NuevoWatermark
    FROM #AccionesMerge;

    DROP TABLE #Origen;
END
GO
