-- 130: ref.PaisesIso3166 -- tabla de referencia estatica (NO viene del
-- AS400) con el listado ISO 3166-1 completo (alpha-2, alpha-3, numerico,
-- nombre en ingles). Se usa para enriquecer dw.dimPais (que sale de
-- PROLX835F.LCN, solo trae alpha-3) con el codigo de 2 letras y el
-- numerico ISO. Fuente: listado ISO 3166-1 estandar (249 entradas, incluye
-- territorios/paises con estatus especial ademas de los 193 miembros ONU).
-- Se crea un esquema nuevo "ref" para distinguir explicitamente los datos
-- de referencia estatica (sembrados por migracion, sin sistema origen) de
-- los datos que vienen del AS400 (stg/int/dw).

IF NOT EXISTS (
    SELECT 1 FROM sys.schemas WHERE name = 'ref'
)
BEGIN
    EXEC('CREATE SCHEMA ref');
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = 'ref' AND t.name = 'PaisesIso3166'
)
BEGIN
    CREATE TABLE ref.PaisesIso3166 (
        Alpha2      NVARCHAR(2)  NOT NULL CONSTRAINT PK_ref_PaisesIso3166 PRIMARY KEY,
        Alpha3      NVARCHAR(3)  NOT NULL,
        Numerico    NVARCHAR(3)  NOT NULL,
        NombreIngles NVARCHAR(100) NOT NULL,
        CONSTRAINT UQ_ref_PaisesIso3166_Alpha3 UNIQUE (Alpha3)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM ref.PaisesIso3166)
BEGIN
    INSERT INTO ref.PaisesIso3166 (Alpha2, Alpha3, Numerico, NombreIngles)
    VALUES
    ('AF', 'AFG', '004', N'Afghanistan'),
    ('AX', 'ALA', '248', N'Åland Islands'),
    ('AL', 'ALB', '008', N'Albania'),
    ('DZ', 'DZA', '012', N'Algeria'),
    ('AS', 'ASM', '016', N'American Samoa'),
    ('AD', 'AND', '020', N'Andorra'),
    ('AO', 'AGO', '024', N'Angola'),
    ('AI', 'AIA', '660', N'Anguilla'),
    ('AQ', 'ATA', '010', N'Antarctica'),
    ('AG', 'ATG', '028', N'Antigua and Barbuda'),
    ('AR', 'ARG', '032', N'Argentina'),
    ('AM', 'ARM', '051', N'Armenia'),
    ('AW', 'ABW', '533', N'Aruba'),
    ('AU', 'AUS', '036', N'Australia'),
    ('AT', 'AUT', '040', N'Austria'),
    ('AZ', 'AZE', '031', N'Azerbaijan'),
    ('BS', 'BHS', '044', N'Bahamas'),
    ('BH', 'BHR', '048', N'Bahrain'),
    ('BD', 'BGD', '050', N'Bangladesh'),
    ('BB', 'BRB', '052', N'Barbados'),
    ('BY', 'BLR', '112', N'Belarus'),
    ('BE', 'BEL', '056', N'Belgium'),
    ('BZ', 'BLZ', '084', N'Belize'),
    ('BJ', 'BEN', '204', N'Benin'),
    ('BM', 'BMU', '060', N'Bermuda'),
    ('BT', 'BTN', '064', N'Bhutan'),
    ('BO', 'BOL', '068', N'Bolivia, Plurinational State of'),
    ('BQ', 'BES', '535', N'Bonaire, Sint Eustatius and Saba'),
    ('BA', 'BIH', '070', N'Bosnia and Herzegovina'),
    ('BW', 'BWA', '072', N'Botswana'),
    ('BV', 'BVT', '074', N'Bouvet Island'),
    ('BR', 'BRA', '076', N'Brazil'),
    ('IO', 'IOT', '086', N'British Indian Ocean Territory'),
    ('BN', 'BRN', '096', N'Brunei Darussalam'),
    ('BG', 'BGR', '100', N'Bulgaria'),
    ('BF', 'BFA', '854', N'Burkina Faso'),
    ('BI', 'BDI', '108', N'Burundi'),
    ('CV', 'CPV', '132', N'Cabo Verde'),
    ('KH', 'KHM', '116', N'Cambodia'),
    ('CM', 'CMR', '120', N'Cameroon'),
    ('CA', 'CAN', '124', N'Canada'),
    ('KY', 'CYM', '136', N'Cayman Islands'),
    ('CF', 'CAF', '140', N'Central African Republic'),
    ('TD', 'TCD', '148', N'Chad'),
    ('CL', 'CHL', '152', N'Chile'),
    ('CN', 'CHN', '156', N'China'),
    ('CX', 'CXR', '162', N'Christmas Island'),
    ('CC', 'CCK', '166', N'Cocos (Keeling) Islands'),
    ('CO', 'COL', '170', N'Colombia'),
    ('KM', 'COM', '174', N'Comoros'),
    ('CG', 'COG', '178', N'Congo'),
    ('CD', 'COD', '180', N'Congo, Democratic Republic of the'),
    ('CK', 'COK', '184', N'Cook Islands'),
    ('CR', 'CRI', '188', N'Costa Rica'),
    ('CI', 'CIV', '384', N'Côte d''Ivoire'),
    ('HR', 'HRV', '191', N'Croatia'),
    ('CU', 'CUB', '192', N'Cuba'),
    ('CW', 'CUW', '531', N'Curaçao'),
    ('CY', 'CYP', '196', N'Cyprus'),
    ('CZ', 'CZE', '203', N'Czechia'),
    ('DK', 'DNK', '208', N'Denmark'),
    ('DJ', 'DJI', '262', N'Djibouti'),
    ('DM', 'DMA', '212', N'Dominica'),
    ('DO', 'DOM', '214', N'Dominican Republic'),
    ('EC', 'ECU', '218', N'Ecuador'),
    ('EG', 'EGY', '818', N'Egypt'),
    ('SV', 'SLV', '222', N'El Salvador'),
    ('GQ', 'GNQ', '226', N'Equatorial Guinea'),
    ('ER', 'ERI', '232', N'Eritrea'),
    ('EE', 'EST', '233', N'Estonia'),
    ('SZ', 'SWZ', '748', N'Eswatini'),
    ('ET', 'ETH', '231', N'Ethiopia'),
    ('FK', 'FLK', '238', N'Falkland Islands (Malvinas)'),
    ('FO', 'FRO', '234', N'Faroe Islands'),
    ('FJ', 'FJI', '242', N'Fiji'),
    ('FI', 'FIN', '246', N'Finland'),
    ('FR', 'FRA', '250', N'France'),
    ('GF', 'GUF', '254', N'French Guiana'),
    ('PF', 'PYF', '258', N'French Polynesia'),
    ('TF', 'ATF', '260', N'French Southern Territories'),
    ('GA', 'GAB', '266', N'Gabon'),
    ('GM', 'GMB', '270', N'Gambia'),
    ('GE', 'GEO', '268', N'Georgia'),
    ('DE', 'DEU', '276', N'Germany'),
    ('GH', 'GHA', '288', N'Ghana'),
    ('GI', 'GIB', '292', N'Gibraltar'),
    ('GR', 'GRC', '300', N'Greece'),
    ('GL', 'GRL', '304', N'Greenland'),
    ('GD', 'GRD', '308', N'Grenada'),
    ('GP', 'GLP', '312', N'Guadeloupe'),
    ('GU', 'GUM', '316', N'Guam'),
    ('GT', 'GTM', '320', N'Guatemala'),
    ('GG', 'GGY', '831', N'Guernsey'),
    ('GN', 'GIN', '324', N'Guinea'),
    ('GW', 'GNB', '624', N'Guinea-Bissau'),
    ('GY', 'GUY', '328', N'Guyana'),
    ('HT', 'HTI', '332', N'Haiti'),
    ('HM', 'HMD', '334', N'Heard Island and McDonald Islands'),
    ('VA', 'VAT', '336', N'Holy See'),
    ('HN', 'HND', '340', N'Honduras'),
    ('HK', 'HKG', '344', N'Hong Kong'),
    ('HU', 'HUN', '348', N'Hungary'),
    ('IS', 'ISL', '352', N'Iceland'),
    ('IN', 'IND', '356', N'India'),
    ('ID', 'IDN', '360', N'Indonesia'),
    ('IR', 'IRN', '364', N'Iran, Islamic Republic of'),
    ('IQ', 'IRQ', '368', N'Iraq'),
    ('IE', 'IRL', '372', N'Ireland'),
    ('IM', 'IMN', '833', N'Isle of Man'),
    ('IL', 'ISR', '376', N'Israel'),
    ('IT', 'ITA', '380', N'Italy'),
    ('JM', 'JAM', '388', N'Jamaica'),
    ('JP', 'JPN', '392', N'Japan'),
    ('JE', 'JEY', '832', N'Jersey'),
    ('JO', 'JOR', '400', N'Jordan'),
    ('KZ', 'KAZ', '398', N'Kazakhstan'),
    ('KE', 'KEN', '404', N'Kenya'),
    ('KI', 'KIR', '296', N'Kiribati'),
    ('KP', 'PRK', '408', N'Korea, Democratic People''s Republic of'),
    ('KR', 'KOR', '410', N'Korea, Republic of'),
    ('KW', 'KWT', '414', N'Kuwait'),
    ('KG', 'KGZ', '417', N'Kyrgyzstan'),
    ('LA', 'LAO', '418', N'Lao People''s Democratic Republic'),
    ('LV', 'LVA', '428', N'Latvia'),
    ('LB', 'LBN', '422', N'Lebanon'),
    ('LS', 'LSO', '426', N'Lesotho'),
    ('LR', 'LBR', '430', N'Liberia'),
    ('LY', 'LBY', '434', N'Libya'),
    ('LI', 'LIE', '438', N'Liechtenstein'),
    ('LT', 'LTU', '440', N'Lithuania'),
    ('LU', 'LUX', '442', N'Luxembourg'),
    ('MO', 'MAC', '446', N'Macao'),
    ('MG', 'MDG', '450', N'Madagascar'),
    ('MW', 'MWI', '454', N'Malawi'),
    ('MY', 'MYS', '458', N'Malaysia'),
    ('MV', 'MDV', '462', N'Maldives'),
    ('ML', 'MLI', '466', N'Mali'),
    ('MT', 'MLT', '470', N'Malta'),
    ('MH', 'MHL', '584', N'Marshall Islands'),
    ('MQ', 'MTQ', '474', N'Martinique'),
    ('MR', 'MRT', '478', N'Mauritania'),
    ('MU', 'MUS', '480', N'Mauritius'),
    ('YT', 'MYT', '175', N'Mayotte'),
    ('MX', 'MEX', '484', N'Mexico'),
    ('FM', 'FSM', '583', N'Micronesia, Federated States of'),
    ('MD', 'MDA', '498', N'Moldova, Republic of'),
    ('MC', 'MCO', '492', N'Monaco'),
    ('MN', 'MNG', '496', N'Mongolia'),
    ('ME', 'MNE', '499', N'Montenegro'),
    ('MS', 'MSR', '500', N'Montserrat'),
    ('MA', 'MAR', '504', N'Morocco'),
    ('MZ', 'MOZ', '508', N'Mozambique'),
    ('MM', 'MMR', '104', N'Myanmar'),
    ('NA', 'NAM', '516', N'Namibia'),
    ('NR', 'NRU', '520', N'Nauru'),
    ('NP', 'NPL', '524', N'Nepal'),
    ('NL', 'NLD', '528', N'Netherlands, Kingdom of the'),
    ('NC', 'NCL', '540', N'New Caledonia'),
    ('NZ', 'NZL', '554', N'New Zealand'),
    ('NI', 'NIC', '558', N'Nicaragua'),
    ('NE', 'NER', '562', N'Niger'),
    ('NG', 'NGA', '566', N'Nigeria'),
    ('NU', 'NIU', '570', N'Niue'),
    ('NF', 'NFK', '574', N'Norfolk Island'),
    ('MK', 'MKD', '807', N'North Macedonia'),
    ('MP', 'MNP', '580', N'Northern Mariana Islands'),
    ('NO', 'NOR', '578', N'Norway'),
    ('OM', 'OMN', '512', N'Oman'),
    ('PK', 'PAK', '586', N'Pakistan'),
    ('PW', 'PLW', '585', N'Palau'),
    ('PS', 'PSE', '275', N'Palestine, State of'),
    ('PA', 'PAN', '591', N'Panama'),
    ('PG', 'PNG', '598', N'Papua New Guinea'),
    ('PY', 'PRY', '600', N'Paraguay'),
    ('PE', 'PER', '604', N'Peru'),
    ('PH', 'PHL', '608', N'Philippines'),
    ('PN', 'PCN', '612', N'Pitcairn'),
    ('PL', 'POL', '616', N'Poland'),
    ('PT', 'PRT', '620', N'Portugal'),
    ('PR', 'PRI', '630', N'Puerto Rico'),
    ('QA', 'QAT', '634', N'Qatar'),
    ('RE', 'REU', '638', N'Réunion'),
    ('RO', 'ROU', '642', N'Romania'),
    ('RU', 'RUS', '643', N'Russian Federation'),
    ('RW', 'RWA', '646', N'Rwanda'),
    ('BL', 'BLM', '652', N'Saint Barthélemy'),
    ('SH', 'SHN', '654', N'Saint Helena, Ascension and Tristan da Cunha'),
    ('KN', 'KNA', '659', N'Saint Kitts and Nevis'),
    ('LC', 'LCA', '662', N'Saint Lucia'),
    ('MF', 'MAF', '663', N'Saint Martin (French part)'),
    ('PM', 'SPM', '666', N'Saint Pierre and Miquelon'),
    ('VC', 'VCT', '670', N'Saint Vincent and the Grenadines'),
    ('WS', 'WSM', '882', N'Samoa'),
    ('SM', 'SMR', '674', N'San Marino'),
    ('ST', 'STP', '678', N'Sao Tome and Principe'),
    ('SA', 'SAU', '682', N'Saudi Arabia'),
    ('SN', 'SEN', '686', N'Senegal'),
    ('RS', 'SRB', '688', N'Serbia'),
    ('SC', 'SYC', '690', N'Seychelles'),
    ('SL', 'SLE', '694', N'Sierra Leone'),
    ('SG', 'SGP', '702', N'Singapore'),
    ('SX', 'SXM', '534', N'Sint Maarten (Dutch part)'),
    ('SK', 'SVK', '703', N'Slovakia'),
    ('SI', 'SVN', '705', N'Slovenia'),
    ('SB', 'SLB', '090', N'Solomon Islands'),
    ('SO', 'SOM', '706', N'Somalia'),
    ('ZA', 'ZAF', '710', N'South Africa'),
    ('GS', 'SGS', '239', N'South Georgia and the South Sandwich Islands'),
    ('SS', 'SSD', '728', N'South Sudan'),
    ('ES', 'ESP', '724', N'Spain'),
    ('LK', 'LKA', '144', N'Sri Lanka'),
    ('SD', 'SDN', '729', N'Sudan'),
    ('SR', 'SUR', '740', N'Suriname'),
    ('SJ', 'SJM', '744', N'Svalbard and Jan Mayen'),
    ('SE', 'SWE', '752', N'Sweden'),
    ('CH', 'CHE', '756', N'Switzerland'),
    ('SY', 'SYR', '760', N'Syrian Arab Republic'),
    ('TW', 'TWN', '158', N'Taiwan, Province of China'),
    ('TJ', 'TJK', '762', N'Tajikistan'),
    ('TZ', 'TZA', '834', N'Tanzania, United Republic of'),
    ('TH', 'THA', '764', N'Thailand'),
    ('TL', 'TLS', '626', N'Timor-Leste'),
    ('TG', 'TGO', '768', N'Togo'),
    ('TK', 'TKL', '772', N'Tokelau'),
    ('TO', 'TON', '776', N'Tonga'),
    ('TT', 'TTO', '780', N'Trinidad and Tobago'),
    ('TN', 'TUN', '788', N'Tunisia'),
    ('TR', 'TUR', '792', N'Türkiye'),
    ('TM', 'TKM', '795', N'Turkmenistan'),
    ('TC', 'TCA', '796', N'Turks and Caicos Islands'),
    ('TV', 'TUV', '798', N'Tuvalu'),
    ('UG', 'UGA', '800', N'Uganda'),
    ('UA', 'UKR', '804', N'Ukraine'),
    ('AE', 'ARE', '784', N'United Arab Emirates'),
    ('GB', 'GBR', '826', N'United Kingdom of Great Britain and Northern Ireland'),
    ('US', 'USA', '840', N'United States of America'),
    ('UM', 'UMI', '581', N'United States Minor Outlying Islands'),
    ('UY', 'URY', '858', N'Uruguay'),
    ('UZ', 'UZB', '860', N'Uzbekistan'),
    ('VU', 'VUT', '548', N'Vanuatu'),
    ('VE', 'VEN', '862', N'Venezuela, Bolivarian Republic of'),
    ('VN', 'VNM', '704', N'Viet Nam'),
    ('VG', 'VGB', '092', N'Virgin Islands (British)'),
    ('VI', 'VIR', '850', N'Virgin Islands (U.S.)'),
    ('WF', 'WLF', '876', N'Wallis and Futuna'),
    ('EH', 'ESH', '732', N'Western Sahara'),
    ('YE', 'YEM', '887', N'Yemen'),
    ('ZM', 'ZMB', '894', N'Zambia'),
    ('ZW', 'ZWE', '716', N'Zimbabwe');
END
GO
