-- 231: [int].factSanAlejoFruta -- version Silver de stg.factSanAlejoFruta (PIDSA.SPVHST00, "Historico de Transacciones Diarias de Fruta").
-- Dominio SanAlejo: fruta de palma (FFB) recibida en las extractoras: una fila por boleta de bascula, con la calidad
-- del racimo (verde, maduro, sobremaduro...), lotes, vagones, finca y productor independiente.
--
-- Llave de negocio CODCIA + NUMDOC (empresa + numero de documento): unica en todo lo cargado
-- (historico acordado desde 2025-01-01; discovery 2026-09-29). Si el origen repitiera una llave, se
-- guarda una vez y Repeticiones cuenta cuantas eran. Carga incremental por MERGE (ver 232): nunca
-- se borra; lo que desaparece del AS400 queda con EsVigente = 0.
-- No se cargan las columnas vacias desde 2025 ni DIA/MES/AÑO (repiten FECDOC). Fechas AAAAMMDD a DATE
-- (invalidas -> NULL, ej. 21171310) y horas HHMMSS a TIME(0).
-- Compatible con SQL Server 2016.

IF NOT EXISTS (
    SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = 'int' AND t.name = 'factSanAlejoFruta'
)
BEGIN
    CREATE TABLE [int].factSanAlejoFruta (
        [CODCIA]   INT            NOT NULL,
        [NUMDOC]   BIGINT         NOT NULL,
        [CODSUC]   INT            NULL,
        [NUMID]    BIGINT         NULL,
        [FECDOC]   DATE           NULL,
        [HORDOC]   TIME(0)        NULL,
        [FINCA]    NVARCHAR(5)    NULL,
        [CODO]     NVARCHAR(5)    NULL,
        [LOTE1]    NVARCHAR(5)    NULL,
        [RACL1]    DECIMAL(6,0)   NULL,
        [SUEL1]    DECIMAL(7,2)   NULL,
        [LOTE2]    NVARCHAR(5)    NULL,
        [RACL2]    DECIMAL(6,0)   NULL,
        [SUEL2]    DECIMAL(7,2)   NULL,
        [LOTE3]    NVARCHAR(5)    NULL,
        [RACL3]    DECIMAL(6,0)   NULL,
        [SUEL3]    DECIMAL(7,2)   NULL,
        [LOTE4]    NVARCHAR(5)    NULL,
        [RACL4]    DECIMAL(6,0)   NULL,
        [SUEL4]    DECIMAL(7,2)   NULL,
        [LOTE5]    NVARCHAR(5)    NULL,
        [RACL5]    DECIMAL(6,0)   NULL,
        [SUEL5]    DECIMAL(7,2)   NULL,
        [LOTE6]    NVARCHAR(5)    NULL,
        [RACL6]    DECIMAL(6,0)   NULL,
        [ALIAS1]   NVARCHAR(4)    NULL,
        [MALLA1]   NVARCHAR(1)    NULL,
        [ALIAS2]   NVARCHAR(4)    NULL,
        [MALLA2]   NVARCHAR(1)    NULL,
        [ALIAS3]   NVARCHAR(4)    NULL,
        [MALLA3]   NVARCHAR(1)    NULL,
        [ALIAS4]   NVARCHAR(4)    NULL,
        [MALLA4]   NVARCHAR(1)    NULL,
        [ALIAS5]   NVARCHAR(4)    NULL,
        [MALLA5]   NVARCHAR(1)    NULL,
        [LLENO1]   NVARCHAR(1)    NULL,
        [LLENO2]   NVARCHAR(1)    NULL,
        [LLENO3]   NVARCHAR(1)    NULL,
        [LLENO4]   NVARCHAR(1)    NULL,
        [LLENO5]   NVARCHAR(1)    NULL,
        [PESOA]    DECIMAL(9,2)   NULL,
        [PESOB]    DECIMAL(9,2)   NULL,
        [PESOC]    DECIMAL(9,2)   NULL,
        [PESOD]    DECIMAL(9,2)   NULL,
        [PESOE]    DECIMAL(9,2)   NULL,
        [CODPRO]   INT            NULL,
        [CODCLI]   INT            NULL,
        [CODLOC]   INT            NULL,
        [SECTOR]   NVARCHAR(4)    NULL,
        [CTACON]   NVARCHAR(20)   NULL,
        [PLACA]    NVARCHAR(9)    NULL,
        [NOMBRE]   NVARCHAR(30)   NULL,
        [CONDUC]   NVARCHAR(30)   NULL,
        [TIPOP]    NVARCHAR(5)    NULL,
        [TIPOF]    NVARCHAR(1)    NULL,
        [PROCED]   NVARCHAR(1)    NULL,
        [COMEN1]   NVARCHAR(50)   NULL,
        [COMEN2]   NVARCHAR(50)   NULL,
        [CODTRA]   INT            NULL,
        [UBICA]    NVARCHAR(1)    NULL,
        [BRUTO]    DECIMAL(7,0)   NULL,
        [TARA]     DECIMAL(7,0)   NULL,
        [NETO]     DECIMAL(7,0)   NULL,
        [SUELTA]   DECIMAL(7,0)   NULL,
        [VERDE]    DECIMAL(5,0)   NULL,
        [VERDEC]   DECIMAL(5,0)   NULL,
        [MADURO]   DECIMAL(5,0)   NULL,
        [SOBMAD]   DECIMAL(5,0)   NULL,
        [PASADO]   DECIMAL(5,0)   NULL,
        [PATLAR]   DECIMAL(5,0)   NULL,
        [RAQUIS]   DECIMAL(5,0)   NULL,
        [RACDEV]   DECIMAL(5,0)   NULL,
        [EFICI]    DECIMAL(5,0)   NULL,
        [FVERDE]   DECIMAL(5,0)   NULL,
        [FVERDC]   DECIMAL(5,0)   NULL,
        [FMADUR]   DECIMAL(5,0)   NULL,
        [FSOBMA]   DECIMAL(5,0)   NULL,
        [FPASAD]   DECIMAL(5,0)   NULL,
        [FPATLA]   DECIMAL(5,0)   NULL,
        [EVAPLA]   INT            NULL,
        [EVAFCA]   INT            NULL,
        [RACPLA]   DECIMAL(7,0)   NULL,
        [SACPLA]   DECIMAL(7,0)   NULL,
        [CONRAC]   NVARCHAR(1)    NULL,
        [CONCAL]   NVARCHAR(1)    NULL,
        [FRUTAR]   DECIMAL(7,0)   NULL,
        [FRUTAS]   DECIMAL(7,0)   NULL,
        [REFDOC]   BIGINT         NULL,
        [REFPES]   DECIMAL(7,0)   NULL,
        [FECENV]   DATE           NULL,
        [MARMOD]   NVARCHAR(1)    NULL,
        [USUMOD]   NVARCHAR(10)   NULL,
        [FECMOD]   DATE           NULL,
        [NUMTIK]   NVARCHAR(10)   NULL,
        [PAGINM]   NVARCHAR(1)    NULL,
        [NOPEDI]   BIGINT         NULL,
        [FEPEDI]   DATE           NULL,
        [FECFAC]   DATE           NULL,
        [CERTIF]   NVARCHAR(2)    NULL,
        [MODEL]    NVARCHAR(5)    NULL,
        [PROSUS]   NVARCHAR(2)    NULL,
        [CERRSP]   NVARCHAR(2)    NULL,
        [SUSRSP]   NVARCHAR(2)    NULL,
        [ISCCOR]   DECIMAL(20,0)  NULL,
        [RSPCOR]   DECIMAL(20,0)  NULL,
        [BOLVEN]   DECIMAL(20,0)  NULL,
        [CARAC2]   NVARCHAR(20)   NULL,
        [CARAC3]   NVARCHAR(20)   NULL,
        [CARAC5]   NVARCHAR(20)   NULL,
        [CARAC6]   NVARCHAR(20)   NULL,
        [CARAC7]   NVARCHAR(20)   NULL,
        [DIGIT1]   DECIMAL(15,2)  NULL,
        [DIGIT5]   DECIMAL(15,0)  NULL,
        [DIGIT6]   DECIMAL(15,0)  NULL,
        [DIGIT7]   DECIMAL(15,0)  NULL,
        [PEROPR]   INT            NULL,
        [SEMAN]    INT            NULL,
        [MESC]     INT            NULL,
        [AÑOC]     INT            NULL,
        [USUARI]   NVARCHAR(10)   NULL,
        [PAGARA]   BIGINT         NULL,
        [HORAB]    TIME(0)        NULL,
        [HORAT]    TIME(0)        NULL,
        [FECHAT]   DATE           NULL,
        [FECHAB]   DATE           NULL,
        [IDING]    BIGINT         NULL,
        [IDSAL]    BIGINT         NULL,
        Repeticiones INT            NOT NULL CONSTRAINT DF_Int_factSanAlejoFruta_Repeticiones DEFAULT (1),
        EsVigente  BIT            NOT NULL CONSTRAINT DF_Int_factSanAlejoFruta_EsVigente DEFAULT (1),
        HashDiff   BINARY(32)     NOT NULL,
        FechaAlta  DATETIME2(7)   NOT NULL CONSTRAINT DF_Int_factSanAlejoFruta_FechaAlta DEFAULT (SYSDATETIME()),
        FechaUltimoCambio DATETIME2(7)   NULL,
        FechaCargaInt DATETIME2(7)   NOT NULL CONSTRAINT DF_Int_factSanAlejoFruta_FechaCargaInt DEFAULT (SYSDATETIME()),
        RunId      INT            NULL,
        CONSTRAINT PK_Int_factSanAlejoFruta PRIMARY KEY (CODCIA, NUMDOC)
    );
    CREATE INDEX IX_Int_factSanAlejoFruta_FechaCargaInt ON [int].factSanAlejoFruta (FechaCargaInt);
    CREATE INDEX IX_Int_factSanAlejoFruta_FechaDoc ON [int].factSanAlejoFruta (FECDOC) INCLUDE (EsVigente);
END
GO
