-- 232: Bronze -> Silver para factSanAlejoFruta (dominio SanAlejo). MERGE incremental por la llave CODCIA +
-- NUMDOC con HashDiff sobre todas las columnas (mismo esquema que factBasculaBufalo, migracion 204):
--   llave nueva             -> INSERT (FechaAlta)
--   llave con hash distinto -> UPDATE (FechaUltimoCambio, RunId)
--   hash igual              -> se ignora
--   llave que falta         -> EsVigente = 0 (nunca se borra), solo si su FECDOC cae dentro de la ventana
--                              que el extract trajo completa (@VentanaDesde; NULL = todo desde 2025).
--                              Si reaparece, vuelve a EsVigente = 1.
-- Resguardo: si la corrida daria de baja mas de @MaxBajas documentos aborta sin tocar nada.
-- Compatible con SQL Server 2016.

CREATE OR ALTER PROCEDURE [int].usp_MergeFactSanAlejoFruta
    @RunId         INT,
    @VentanaDesde  DATE = NULL,
    @MaxBajas      INT  = 200
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @FilasLeidas INT = (SELECT COUNT(*) FROM stg.factSanAlejoFruta);
    IF @FilasLeidas = 0
        THROW 50001, 'stg.factSanAlejoFruta esta vacio: no se procesa (revisar el extract).', 1;

    CREATE TABLE #Normalizado (
        [CODCIA] INT NOT NULL,
        [CODSUC] INT NULL,
        [NUMDOC] BIGINT NOT NULL,
        [NUMID] BIGINT NULL,
        [FECDOC] DATE NULL,
        [HORDOC] TIME(0) NULL,
        [FINCA] NVARCHAR(5) NULL,
        [CODO] NVARCHAR(5) NULL,
        [LOTE1] NVARCHAR(5) NULL,
        [RACL1] DECIMAL(6,0) NULL,
        [SUEL1] DECIMAL(7,2) NULL,
        [LOTE2] NVARCHAR(5) NULL,
        [RACL2] DECIMAL(6,0) NULL,
        [SUEL2] DECIMAL(7,2) NULL,
        [LOTE3] NVARCHAR(5) NULL,
        [RACL3] DECIMAL(6,0) NULL,
        [SUEL3] DECIMAL(7,2) NULL,
        [LOTE4] NVARCHAR(5) NULL,
        [RACL4] DECIMAL(6,0) NULL,
        [SUEL4] DECIMAL(7,2) NULL,
        [LOTE5] NVARCHAR(5) NULL,
        [RACL5] DECIMAL(6,0) NULL,
        [SUEL5] DECIMAL(7,2) NULL,
        [LOTE6] NVARCHAR(5) NULL,
        [RACL6] DECIMAL(6,0) NULL,
        [ALIAS1] NVARCHAR(4) NULL,
        [MALLA1] NVARCHAR(1) NULL,
        [ALIAS2] NVARCHAR(4) NULL,
        [MALLA2] NVARCHAR(1) NULL,
        [ALIAS3] NVARCHAR(4) NULL,
        [MALLA3] NVARCHAR(1) NULL,
        [ALIAS4] NVARCHAR(4) NULL,
        [MALLA4] NVARCHAR(1) NULL,
        [ALIAS5] NVARCHAR(4) NULL,
        [MALLA5] NVARCHAR(1) NULL,
        [LLENO1] NVARCHAR(1) NULL,
        [LLENO2] NVARCHAR(1) NULL,
        [LLENO3] NVARCHAR(1) NULL,
        [LLENO4] NVARCHAR(1) NULL,
        [LLENO5] NVARCHAR(1) NULL,
        [PESOA] DECIMAL(9,2) NULL,
        [PESOB] DECIMAL(9,2) NULL,
        [PESOC] DECIMAL(9,2) NULL,
        [PESOD] DECIMAL(9,2) NULL,
        [PESOE] DECIMAL(9,2) NULL,
        [CODPRO] INT NULL,
        [CODCLI] INT NULL,
        [CODLOC] INT NULL,
        [SECTOR] NVARCHAR(4) NULL,
        [CTACON] NVARCHAR(20) NULL,
        [PLACA] NVARCHAR(9) NULL,
        [NOMBRE] NVARCHAR(30) NULL,
        [CONDUC] NVARCHAR(30) NULL,
        [TIPOP] NVARCHAR(5) NULL,
        [TIPOF] NVARCHAR(1) NULL,
        [PROCED] NVARCHAR(1) NULL,
        [COMEN1] NVARCHAR(50) NULL,
        [COMEN2] NVARCHAR(50) NULL,
        [CODTRA] INT NULL,
        [UBICA] NVARCHAR(1) NULL,
        [BRUTO] DECIMAL(7,0) NULL,
        [TARA] DECIMAL(7,0) NULL,
        [NETO] DECIMAL(7,0) NULL,
        [SUELTA] DECIMAL(7,0) NULL,
        [VERDE] DECIMAL(5,0) NULL,
        [VERDEC] DECIMAL(5,0) NULL,
        [MADURO] DECIMAL(5,0) NULL,
        [SOBMAD] DECIMAL(5,0) NULL,
        [PASADO] DECIMAL(5,0) NULL,
        [PATLAR] DECIMAL(5,0) NULL,
        [RAQUIS] DECIMAL(5,0) NULL,
        [RACDEV] DECIMAL(5,0) NULL,
        [EFICI] DECIMAL(5,0) NULL,
        [FVERDE] DECIMAL(5,0) NULL,
        [FVERDC] DECIMAL(5,0) NULL,
        [FMADUR] DECIMAL(5,0) NULL,
        [FSOBMA] DECIMAL(5,0) NULL,
        [FPASAD] DECIMAL(5,0) NULL,
        [FPATLA] DECIMAL(5,0) NULL,
        [EVAPLA] INT NULL,
        [EVAFCA] INT NULL,
        [RACPLA] DECIMAL(7,0) NULL,
        [SACPLA] DECIMAL(7,0) NULL,
        [CONRAC] NVARCHAR(1) NULL,
        [CONCAL] NVARCHAR(1) NULL,
        [FRUTAR] DECIMAL(7,0) NULL,
        [FRUTAS] DECIMAL(7,0) NULL,
        [REFDOC] BIGINT NULL,
        [REFPES] DECIMAL(7,0) NULL,
        [FECENV] DATE NULL,
        [MARMOD] NVARCHAR(1) NULL,
        [USUMOD] NVARCHAR(10) NULL,
        [FECMOD] DATE NULL,
        [NUMTIK] NVARCHAR(10) NULL,
        [PAGINM] NVARCHAR(1) NULL,
        [NOPEDI] BIGINT NULL,
        [FEPEDI] DATE NULL,
        [FECFAC] DATE NULL,
        [CERTIF] NVARCHAR(2) NULL,
        [MODEL] NVARCHAR(5) NULL,
        [PROSUS] NVARCHAR(2) NULL,
        [CERRSP] NVARCHAR(2) NULL,
        [SUSRSP] NVARCHAR(2) NULL,
        [ISCCOR] DECIMAL(20,0) NULL,
        [RSPCOR] DECIMAL(20,0) NULL,
        [BOLVEN] DECIMAL(20,0) NULL,
        [CARAC2] NVARCHAR(20) NULL,
        [CARAC3] NVARCHAR(20) NULL,
        [CARAC5] NVARCHAR(20) NULL,
        [CARAC6] NVARCHAR(20) NULL,
        [CARAC7] NVARCHAR(20) NULL,
        [DIGIT1] DECIMAL(15,2) NULL,
        [DIGIT5] DECIMAL(15,0) NULL,
        [DIGIT6] DECIMAL(15,0) NULL,
        [DIGIT7] DECIMAL(15,0) NULL,
        [PEROPR] INT NULL,
        [SEMAN] INT NULL,
        [MESC] INT NULL,
        [AÑOC] INT NULL,
        [USUARI] NVARCHAR(10) NULL,
        [PAGARA] BIGINT NULL,
        [HORAB] TIME(0) NULL,
        [HORAT] TIME(0) NULL,
        [FECHAT] DATE NULL,
        [FECHAB] DATE NULL,
        [IDING] BIGINT NULL,
        [IDSAL] BIGINT NULL
    );

    INSERT INTO #Normalizado ([CODCIA], [CODSUC], [NUMDOC], [NUMID], [FECDOC], [HORDOC], [FINCA], [CODO], [LOTE1], [RACL1], [SUEL1], [LOTE2], [RACL2], [SUEL2], [LOTE3], [RACL3], [SUEL3], [LOTE4], [RACL4], [SUEL4], [LOTE5], [RACL5], [SUEL5], [LOTE6], [RACL6], [ALIAS1], [MALLA1], [ALIAS2], [MALLA2], [ALIAS3], [MALLA3], [ALIAS4], [MALLA4], [ALIAS5], [MALLA5], [LLENO1], [LLENO2], [LLENO3], [LLENO4], [LLENO5], [PESOA], [PESOB], [PESOC], [PESOD], [PESOE], [CODPRO], [CODCLI], [CODLOC], [SECTOR], [CTACON], [PLACA], [NOMBRE], [CONDUC], [TIPOP], [TIPOF], [PROCED], [COMEN1], [COMEN2], [CODTRA], [UBICA], [BRUTO], [TARA], [NETO], [SUELTA], [VERDE], [VERDEC], [MADURO], [SOBMAD], [PASADO], [PATLAR], [RAQUIS], [RACDEV], [EFICI], [FVERDE], [FVERDC], [FMADUR], [FSOBMA], [FPASAD], [FPATLA], [EVAPLA], [EVAFCA], [RACPLA], [SACPLA], [CONRAC], [CONCAL], [FRUTAR], [FRUTAS], [REFDOC], [REFPES], [FECENV], [MARMOD], [USUMOD], [FECMOD], [NUMTIK], [PAGINM], [NOPEDI], [FEPEDI], [FECFAC], [CERTIF], [MODEL], [PROSUS], [CERRSP], [SUSRSP], [ISCCOR], [RSPCOR], [BOLVEN], [CARAC2], [CARAC3], [CARAC5], [CARAC6], [CARAC7], [DIGIT1], [DIGIT5], [DIGIT6], [DIGIT7], [PEROPR], [SEMAN], [MESC], [AÑOC], [USUARI], [PAGARA], [HORAB], [HORAT], [FECHAT], [FECHAB], [IDING], [IDSAL])
    SELECT
        CAST(s.[CODCIA] AS INT),
        CAST(NULLIF(s.[CODSUC], 0) AS INT),
        CAST(s.[NUMDOC] AS BIGINT),
        CAST(NULLIF(s.[NUMID], 0) AS BIGINT),
        TRY_CONVERT(DATE, CONVERT(CHAR(8), CAST(NULLIF(s.[FECDOC], 0) AS BIGINT))),
        CASE WHEN s.[HORDOC] IS NULL OR s.[HORDOC] = 0 THEN NULL ELSE TRY_CONVERT(TIME(0), STUFF(STUFF(RIGHT('000000' + CONVERT(VARCHAR(8), CAST(s.[HORDOC] AS BIGINT)), 6), 3, 0, ':'), 6, 0, ':')) END,
        NULLIF(LTRIM(RTRIM(s.[FINCA])), ''),
        NULLIF(LTRIM(RTRIM(s.[CODO])), ''),
        NULLIF(LTRIM(RTRIM(s.[LOTE1])), ''),
        CAST(s.[RACL1] AS DECIMAL(6,0)),
        CAST(s.[SUEL1] AS DECIMAL(7,2)),
        NULLIF(LTRIM(RTRIM(s.[LOTE2])), ''),
        CAST(s.[RACL2] AS DECIMAL(6,0)),
        CAST(s.[SUEL2] AS DECIMAL(7,2)),
        NULLIF(LTRIM(RTRIM(s.[LOTE3])), ''),
        CAST(s.[RACL3] AS DECIMAL(6,0)),
        CAST(s.[SUEL3] AS DECIMAL(7,2)),
        NULLIF(LTRIM(RTRIM(s.[LOTE4])), ''),
        CAST(s.[RACL4] AS DECIMAL(6,0)),
        CAST(s.[SUEL4] AS DECIMAL(7,2)),
        NULLIF(LTRIM(RTRIM(s.[LOTE5])), ''),
        CAST(s.[RACL5] AS DECIMAL(6,0)),
        CAST(s.[SUEL5] AS DECIMAL(7,2)),
        NULLIF(LTRIM(RTRIM(s.[LOTE6])), ''),
        CAST(s.[RACL6] AS DECIMAL(6,0)),
        NULLIF(LTRIM(RTRIM(s.[ALIAS1])), ''),
        NULLIF(LTRIM(RTRIM(s.[MALLA1])), ''),
        NULLIF(LTRIM(RTRIM(s.[ALIAS2])), ''),
        NULLIF(LTRIM(RTRIM(s.[MALLA2])), ''),
        NULLIF(LTRIM(RTRIM(s.[ALIAS3])), ''),
        NULLIF(LTRIM(RTRIM(s.[MALLA3])), ''),
        NULLIF(LTRIM(RTRIM(s.[ALIAS4])), ''),
        NULLIF(LTRIM(RTRIM(s.[MALLA4])), ''),
        NULLIF(LTRIM(RTRIM(s.[ALIAS5])), ''),
        NULLIF(LTRIM(RTRIM(s.[MALLA5])), ''),
        NULLIF(LTRIM(RTRIM(s.[LLENO1])), ''),
        NULLIF(LTRIM(RTRIM(s.[LLENO2])), ''),
        NULLIF(LTRIM(RTRIM(s.[LLENO3])), ''),
        NULLIF(LTRIM(RTRIM(s.[LLENO4])), ''),
        NULLIF(LTRIM(RTRIM(s.[LLENO5])), ''),
        CAST(s.[PESOA] AS DECIMAL(9,2)),
        CAST(s.[PESOB] AS DECIMAL(9,2)),
        CAST(s.[PESOC] AS DECIMAL(9,2)),
        CAST(s.[PESOD] AS DECIMAL(9,2)),
        CAST(s.[PESOE] AS DECIMAL(9,2)),
        CAST(NULLIF(s.[CODPRO], 0) AS INT),
        CAST(NULLIF(s.[CODCLI], 0) AS INT),
        CAST(NULLIF(s.[CODLOC], 0) AS INT),
        NULLIF(LTRIM(RTRIM(s.[SECTOR])), ''),
        NULLIF(LTRIM(RTRIM(s.[CTACON])), ''),
        NULLIF(LTRIM(RTRIM(s.[PLACA])), ''),
        NULLIF(LTRIM(RTRIM(s.[NOMBRE])), ''),
        NULLIF(LTRIM(RTRIM(s.[CONDUC])), ''),
        NULLIF(LTRIM(RTRIM(s.[TIPOP])), ''),
        NULLIF(LTRIM(RTRIM(s.[TIPOF])), ''),
        NULLIF(LTRIM(RTRIM(s.[PROCED])), ''),
        NULLIF(LTRIM(RTRIM(s.[COMEN1])), ''),
        NULLIF(LTRIM(RTRIM(s.[COMEN2])), ''),
        CAST(NULLIF(s.[CODTRA], 0) AS INT),
        NULLIF(LTRIM(RTRIM(s.[UBICA])), ''),
        CAST(s.[BRUTO] AS DECIMAL(7,0)),
        CAST(s.[TARA] AS DECIMAL(7,0)),
        CAST(s.[NETO] AS DECIMAL(7,0)),
        CAST(s.[SUELTA] AS DECIMAL(7,0)),
        CAST(s.[VERDE] AS DECIMAL(5,0)),
        CAST(s.[VERDEC] AS DECIMAL(5,0)),
        CAST(s.[MADURO] AS DECIMAL(5,0)),
        CAST(s.[SOBMAD] AS DECIMAL(5,0)),
        CAST(s.[PASADO] AS DECIMAL(5,0)),
        CAST(s.[PATLAR] AS DECIMAL(5,0)),
        CAST(s.[RAQUIS] AS DECIMAL(5,0)),
        CAST(s.[RACDEV] AS DECIMAL(5,0)),
        CAST(s.[EFICI] AS DECIMAL(5,0)),
        CAST(s.[FVERDE] AS DECIMAL(5,0)),
        CAST(s.[FVERDC] AS DECIMAL(5,0)),
        CAST(s.[FMADUR] AS DECIMAL(5,0)),
        CAST(s.[FSOBMA] AS DECIMAL(5,0)),
        CAST(s.[FPASAD] AS DECIMAL(5,0)),
        CAST(s.[FPATLA] AS DECIMAL(5,0)),
        CAST(NULLIF(s.[EVAPLA], 0) AS INT),
        CAST(NULLIF(s.[EVAFCA], 0) AS INT),
        CAST(s.[RACPLA] AS DECIMAL(7,0)),
        CAST(s.[SACPLA] AS DECIMAL(7,0)),
        NULLIF(LTRIM(RTRIM(s.[CONRAC])), ''),
        NULLIF(LTRIM(RTRIM(s.[CONCAL])), ''),
        CAST(s.[FRUTAR] AS DECIMAL(7,0)),
        CAST(s.[FRUTAS] AS DECIMAL(7,0)),
        CAST(NULLIF(s.[REFDOC], 0) AS BIGINT),
        CAST(s.[REFPES] AS DECIMAL(7,0)),
        TRY_CONVERT(DATE, CONVERT(CHAR(8), CAST(NULLIF(s.[FECENV], 0) AS BIGINT))),
        NULLIF(LTRIM(RTRIM(s.[MARMOD])), ''),
        NULLIF(LTRIM(RTRIM(s.[USUMOD])), ''),
        TRY_CONVERT(DATE, CONVERT(CHAR(8), CAST(NULLIF(s.[FECMOD], 0) AS BIGINT))),
        NULLIF(LTRIM(RTRIM(s.[NUMTIK])), ''),
        NULLIF(LTRIM(RTRIM(s.[PAGINM])), ''),
        CAST(NULLIF(s.[NOPEDI], 0) AS BIGINT),
        TRY_CONVERT(DATE, CONVERT(CHAR(8), CAST(NULLIF(s.[FEPEDI], 0) AS BIGINT))),
        TRY_CONVERT(DATE, CONVERT(CHAR(8), CAST(NULLIF(s.[FECFAC], 0) AS BIGINT))),
        NULLIF(LTRIM(RTRIM(s.[CERTIF])), ''),
        NULLIF(LTRIM(RTRIM(s.[MODEL])), ''),
        NULLIF(LTRIM(RTRIM(s.[PROSUS])), ''),
        NULLIF(LTRIM(RTRIM(s.[CERRSP])), ''),
        NULLIF(LTRIM(RTRIM(s.[SUSRSP])), ''),
        CAST(NULLIF(s.[ISCCOR], 0) AS DECIMAL(20,0)),
        CAST(NULLIF(s.[RSPCOR], 0) AS DECIMAL(20,0)),
        CAST(NULLIF(s.[BOLVEN], 0) AS DECIMAL(20,0)),
        NULLIF(LTRIM(RTRIM(s.[CARAC2])), ''),
        NULLIF(LTRIM(RTRIM(s.[CARAC3])), ''),
        NULLIF(LTRIM(RTRIM(s.[CARAC5])), ''),
        NULLIF(LTRIM(RTRIM(s.[CARAC6])), ''),
        NULLIF(LTRIM(RTRIM(s.[CARAC7])), ''),
        CAST(s.[DIGIT1] AS DECIMAL(15,2)),
        CAST(s.[DIGIT5] AS DECIMAL(15,0)),
        CAST(s.[DIGIT6] AS DECIMAL(15,0)),
        CAST(s.[DIGIT7] AS DECIMAL(15,0)),
        CAST(NULLIF(s.[PEROPR], 0) AS INT),
        CAST(NULLIF(s.[SEMAN], 0) AS INT),
        CAST(NULLIF(s.[MESC], 0) AS INT),
        CAST(NULLIF(s.[AÑOC], 0) AS INT),
        NULLIF(LTRIM(RTRIM(s.[USUARI])), ''),
        CAST(NULLIF(s.[PAGARA], 0) AS BIGINT),
        CASE WHEN s.[HORAB] IS NULL OR s.[HORAB] = 0 THEN NULL ELSE TRY_CONVERT(TIME(0), STUFF(STUFF(RIGHT('000000' + CONVERT(VARCHAR(8), CAST(s.[HORAB] AS BIGINT)), 6), 3, 0, ':'), 6, 0, ':')) END,
        CASE WHEN s.[HORAT] IS NULL OR s.[HORAT] = 0 THEN NULL ELSE TRY_CONVERT(TIME(0), STUFF(STUFF(RIGHT('000000' + CONVERT(VARCHAR(8), CAST(s.[HORAT] AS BIGINT)), 6), 3, 0, ':'), 6, 0, ':')) END,
        TRY_CONVERT(DATE, CONVERT(CHAR(8), CAST(NULLIF(s.[FECHAT], 0) AS BIGINT))),
        TRY_CONVERT(DATE, CONVERT(CHAR(8), CAST(NULLIF(s.[FECHAB], 0) AS BIGINT))),
        CAST(NULLIF(s.[IDING], 0) AS BIGINT),
        CAST(NULLIF(s.[IDSAL], 0) AS BIGINT)
    FROM stg.factSanAlejoFruta s
    WHERE s.[CODCIA] IS NOT NULL AND s.[NUMDOC] IS NOT NULL;

    ;WITH Numerado AS (
        SELECT n.*,
               COUNT(*) OVER (PARTITION BY CODCIA, NUMDOC) AS Repeticiones,
               ROW_NUMBER() OVER (PARTITION BY CODCIA, NUMDOC ORDER BY FECMOD DESC, HORDOC DESC) AS rn
        FROM #Normalizado n
    ),
    Unico AS (
        SELECT [CODCIA], [CODSUC], [NUMDOC], [NUMID], [FECDOC], [HORDOC], [FINCA], [CODO], [LOTE1], [RACL1], [SUEL1], [LOTE2], [RACL2], [SUEL2], [LOTE3], [RACL3], [SUEL3], [LOTE4], [RACL4], [SUEL4], [LOTE5], [RACL5], [SUEL5], [LOTE6], [RACL6], [ALIAS1], [MALLA1], [ALIAS2], [MALLA2], [ALIAS3], [MALLA3], [ALIAS4], [MALLA4], [ALIAS5], [MALLA5], [LLENO1], [LLENO2], [LLENO3], [LLENO4], [LLENO5], [PESOA], [PESOB], [PESOC], [PESOD], [PESOE], [CODPRO], [CODCLI], [CODLOC], [SECTOR], [CTACON], [PLACA], [NOMBRE], [CONDUC], [TIPOP], [TIPOF], [PROCED], [COMEN1], [COMEN2], [CODTRA], [UBICA], [BRUTO], [TARA], [NETO], [SUELTA], [VERDE], [VERDEC], [MADURO], [SOBMAD], [PASADO], [PATLAR], [RAQUIS], [RACDEV], [EFICI], [FVERDE], [FVERDC], [FMADUR], [FSOBMA], [FPASAD], [FPATLA], [EVAPLA], [EVAFCA], [RACPLA], [SACPLA], [CONRAC], [CONCAL], [FRUTAR], [FRUTAS], [REFDOC], [REFPES], [FECENV], [MARMOD], [USUMOD], [FECMOD], [NUMTIK], [PAGINM], [NOPEDI], [FEPEDI], [FECFAC], [CERTIF], [MODEL], [PROSUS], [CERRSP], [SUSRSP], [ISCCOR], [RSPCOR], [BOLVEN], [CARAC2], [CARAC3], [CARAC5], [CARAC6], [CARAC7], [DIGIT1], [DIGIT5], [DIGIT6], [DIGIT7], [PEROPR], [SEMAN], [MESC], [AÑOC], [USUARI], [PAGARA], [HORAB], [HORAT], [FECHAT], [FECHAB], [IDING], [IDSAL], Repeticiones FROM Numerado WHERE rn = 1
    )
    SELECT u.*, HASHBYTES('SHA2_256', (SELECT u.* FOR XML RAW, BINARY BASE64)) AS HashDiff
    INTO #Origen
    FROM Unico u;

    CREATE UNIQUE CLUSTERED INDEX IX_Origen ON #Origen (CODCIA, NUMDOC);
    DECLARE @Llaves INT = (SELECT COUNT(*) FROM #Origen);

    DECLARE @Bajas INT = (
        SELECT COUNT(*) FROM [int].factSanAlejoFruta d
        WHERE d.EsVigente = 1
          AND (@VentanaDesde IS NULL OR d.FECDOC >= @VentanaDesde)
          AND NOT EXISTS (SELECT 1 FROM #Origen o WHERE o.CODCIA = d.CODCIA AND o.NUMDOC = d.NUMDOC)
    );
    IF @Bajas > @MaxBajas
    BEGIN
        DECLARE @Msg NVARCHAR(400) = CONCAT(N'La corrida daria de baja ', @Bajas, N' documentos (limite ', @MaxBajas,
            N'): se aborta sin cambios. Revisar el extract; si las bajas son reales, correr silver con --max-bajas.');
        THROW 50003, @Msg, 1;
    END

    CREATE TABLE #AccionesMerge (Accion VARCHAR(20) NOT NULL, EsVigente BIT NULL);

    MERGE [int].factSanAlejoFruta AS destino
        USING #Origen AS origen
        ON destino.CODCIA = origen.CODCIA AND destino.NUMDOC = origen.NUMDOC
    WHEN MATCHED AND (destino.HashDiff <> origen.HashDiff OR destino.EsVigente = 0) THEN
        UPDATE SET
            [CODSUC]   = origen.[CODSUC],
            [NUMID]    = origen.[NUMID],
            [FECDOC]   = origen.[FECDOC],
            [HORDOC]   = origen.[HORDOC],
            [FINCA]    = origen.[FINCA],
            [CODO]     = origen.[CODO],
            [LOTE1]    = origen.[LOTE1],
            [RACL1]    = origen.[RACL1],
            [SUEL1]    = origen.[SUEL1],
            [LOTE2]    = origen.[LOTE2],
            [RACL2]    = origen.[RACL2],
            [SUEL2]    = origen.[SUEL2],
            [LOTE3]    = origen.[LOTE3],
            [RACL3]    = origen.[RACL3],
            [SUEL3]    = origen.[SUEL3],
            [LOTE4]    = origen.[LOTE4],
            [RACL4]    = origen.[RACL4],
            [SUEL4]    = origen.[SUEL4],
            [LOTE5]    = origen.[LOTE5],
            [RACL5]    = origen.[RACL5],
            [SUEL5]    = origen.[SUEL5],
            [LOTE6]    = origen.[LOTE6],
            [RACL6]    = origen.[RACL6],
            [ALIAS1]   = origen.[ALIAS1],
            [MALLA1]   = origen.[MALLA1],
            [ALIAS2]   = origen.[ALIAS2],
            [MALLA2]   = origen.[MALLA2],
            [ALIAS3]   = origen.[ALIAS3],
            [MALLA3]   = origen.[MALLA3],
            [ALIAS4]   = origen.[ALIAS4],
            [MALLA4]   = origen.[MALLA4],
            [ALIAS5]   = origen.[ALIAS5],
            [MALLA5]   = origen.[MALLA5],
            [LLENO1]   = origen.[LLENO1],
            [LLENO2]   = origen.[LLENO2],
            [LLENO3]   = origen.[LLENO3],
            [LLENO4]   = origen.[LLENO4],
            [LLENO5]   = origen.[LLENO5],
            [PESOA]    = origen.[PESOA],
            [PESOB]    = origen.[PESOB],
            [PESOC]    = origen.[PESOC],
            [PESOD]    = origen.[PESOD],
            [PESOE]    = origen.[PESOE],
            [CODPRO]   = origen.[CODPRO],
            [CODCLI]   = origen.[CODCLI],
            [CODLOC]   = origen.[CODLOC],
            [SECTOR]   = origen.[SECTOR],
            [CTACON]   = origen.[CTACON],
            [PLACA]    = origen.[PLACA],
            [NOMBRE]   = origen.[NOMBRE],
            [CONDUC]   = origen.[CONDUC],
            [TIPOP]    = origen.[TIPOP],
            [TIPOF]    = origen.[TIPOF],
            [PROCED]   = origen.[PROCED],
            [COMEN1]   = origen.[COMEN1],
            [COMEN2]   = origen.[COMEN2],
            [CODTRA]   = origen.[CODTRA],
            [UBICA]    = origen.[UBICA],
            [BRUTO]    = origen.[BRUTO],
            [TARA]     = origen.[TARA],
            [NETO]     = origen.[NETO],
            [SUELTA]   = origen.[SUELTA],
            [VERDE]    = origen.[VERDE],
            [VERDEC]   = origen.[VERDEC],
            [MADURO]   = origen.[MADURO],
            [SOBMAD]   = origen.[SOBMAD],
            [PASADO]   = origen.[PASADO],
            [PATLAR]   = origen.[PATLAR],
            [RAQUIS]   = origen.[RAQUIS],
            [RACDEV]   = origen.[RACDEV],
            [EFICI]    = origen.[EFICI],
            [FVERDE]   = origen.[FVERDE],
            [FVERDC]   = origen.[FVERDC],
            [FMADUR]   = origen.[FMADUR],
            [FSOBMA]   = origen.[FSOBMA],
            [FPASAD]   = origen.[FPASAD],
            [FPATLA]   = origen.[FPATLA],
            [EVAPLA]   = origen.[EVAPLA],
            [EVAFCA]   = origen.[EVAFCA],
            [RACPLA]   = origen.[RACPLA],
            [SACPLA]   = origen.[SACPLA],
            [CONRAC]   = origen.[CONRAC],
            [CONCAL]   = origen.[CONCAL],
            [FRUTAR]   = origen.[FRUTAR],
            [FRUTAS]   = origen.[FRUTAS],
            [REFDOC]   = origen.[REFDOC],
            [REFPES]   = origen.[REFPES],
            [FECENV]   = origen.[FECENV],
            [MARMOD]   = origen.[MARMOD],
            [USUMOD]   = origen.[USUMOD],
            [FECMOD]   = origen.[FECMOD],
            [NUMTIK]   = origen.[NUMTIK],
            [PAGINM]   = origen.[PAGINM],
            [NOPEDI]   = origen.[NOPEDI],
            [FEPEDI]   = origen.[FEPEDI],
            [FECFAC]   = origen.[FECFAC],
            [CERTIF]   = origen.[CERTIF],
            [MODEL]    = origen.[MODEL],
            [PROSUS]   = origen.[PROSUS],
            [CERRSP]   = origen.[CERRSP],
            [SUSRSP]   = origen.[SUSRSP],
            [ISCCOR]   = origen.[ISCCOR],
            [RSPCOR]   = origen.[RSPCOR],
            [BOLVEN]   = origen.[BOLVEN],
            [CARAC2]   = origen.[CARAC2],
            [CARAC3]   = origen.[CARAC3],
            [CARAC5]   = origen.[CARAC5],
            [CARAC6]   = origen.[CARAC6],
            [CARAC7]   = origen.[CARAC7],
            [DIGIT1]   = origen.[DIGIT1],
            [DIGIT5]   = origen.[DIGIT5],
            [DIGIT6]   = origen.[DIGIT6],
            [DIGIT7]   = origen.[DIGIT7],
            [PEROPR]   = origen.[PEROPR],
            [SEMAN]    = origen.[SEMAN],
            [MESC]     = origen.[MESC],
            [AÑOC]     = origen.[AÑOC],
            [USUARI]   = origen.[USUARI],
            [PAGARA]   = origen.[PAGARA],
            [HORAB]    = origen.[HORAB],
            [HORAT]    = origen.[HORAT],
            [FECHAT]   = origen.[FECHAT],
            [FECHAB]   = origen.[FECHAB],
            [IDING]    = origen.[IDING],
            [IDSAL]    = origen.[IDSAL],
            Repeticiones = origen.Repeticiones,
            EsVigente  = 1,
            HashDiff   = origen.HashDiff,
            FechaUltimoCambio = SYSDATETIME(),
            FechaCargaInt = SYSDATETIME(),
            RunId      = @RunId
    WHEN NOT MATCHED BY TARGET THEN
        INSERT ([CODCIA], [CODSUC], [NUMDOC], [NUMID], [FECDOC], [HORDOC], [FINCA], [CODO], [LOTE1], [RACL1], [SUEL1], [LOTE2], [RACL2], [SUEL2], [LOTE3], [RACL3], [SUEL3], [LOTE4], [RACL4], [SUEL4], [LOTE5], [RACL5], [SUEL5], [LOTE6], [RACL6], [ALIAS1], [MALLA1], [ALIAS2], [MALLA2], [ALIAS3], [MALLA3], [ALIAS4], [MALLA4], [ALIAS5], [MALLA5], [LLENO1], [LLENO2], [LLENO3], [LLENO4], [LLENO5], [PESOA], [PESOB], [PESOC], [PESOD], [PESOE], [CODPRO], [CODCLI], [CODLOC], [SECTOR], [CTACON], [PLACA], [NOMBRE], [CONDUC], [TIPOP], [TIPOF], [PROCED], [COMEN1], [COMEN2], [CODTRA], [UBICA], [BRUTO], [TARA], [NETO], [SUELTA], [VERDE], [VERDEC], [MADURO], [SOBMAD], [PASADO], [PATLAR], [RAQUIS], [RACDEV], [EFICI], [FVERDE], [FVERDC], [FMADUR], [FSOBMA], [FPASAD], [FPATLA], [EVAPLA], [EVAFCA], [RACPLA], [SACPLA], [CONRAC], [CONCAL], [FRUTAR], [FRUTAS], [REFDOC], [REFPES], [FECENV], [MARMOD], [USUMOD], [FECMOD], [NUMTIK], [PAGINM], [NOPEDI], [FEPEDI], [FECFAC], [CERTIF], [MODEL], [PROSUS], [CERRSP], [SUSRSP], [ISCCOR], [RSPCOR], [BOLVEN], [CARAC2], [CARAC3], [CARAC5], [CARAC6], [CARAC7], [DIGIT1], [DIGIT5], [DIGIT6], [DIGIT7], [PEROPR], [SEMAN], [MESC], [AÑOC], [USUARI], [PAGARA], [HORAB], [HORAT], [FECHAT], [FECHAB], [IDING], [IDSAL], Repeticiones, HashDiff, RunId)
        VALUES (origen.[CODCIA], origen.[CODSUC], origen.[NUMDOC], origen.[NUMID], origen.[FECDOC], origen.[HORDOC], origen.[FINCA], origen.[CODO], origen.[LOTE1], origen.[RACL1], origen.[SUEL1], origen.[LOTE2], origen.[RACL2], origen.[SUEL2], origen.[LOTE3], origen.[RACL3], origen.[SUEL3], origen.[LOTE4], origen.[RACL4], origen.[SUEL4], origen.[LOTE5], origen.[RACL5], origen.[SUEL5], origen.[LOTE6], origen.[RACL6], origen.[ALIAS1], origen.[MALLA1], origen.[ALIAS2], origen.[MALLA2], origen.[ALIAS3], origen.[MALLA3], origen.[ALIAS4], origen.[MALLA4], origen.[ALIAS5], origen.[MALLA5], origen.[LLENO1], origen.[LLENO2], origen.[LLENO3], origen.[LLENO4], origen.[LLENO5], origen.[PESOA], origen.[PESOB], origen.[PESOC], origen.[PESOD], origen.[PESOE], origen.[CODPRO], origen.[CODCLI], origen.[CODLOC], origen.[SECTOR], origen.[CTACON], origen.[PLACA], origen.[NOMBRE], origen.[CONDUC], origen.[TIPOP], origen.[TIPOF], origen.[PROCED], origen.[COMEN1], origen.[COMEN2], origen.[CODTRA], origen.[UBICA], origen.[BRUTO], origen.[TARA], origen.[NETO], origen.[SUELTA], origen.[VERDE], origen.[VERDEC], origen.[MADURO], origen.[SOBMAD], origen.[PASADO], origen.[PATLAR], origen.[RAQUIS], origen.[RACDEV], origen.[EFICI], origen.[FVERDE], origen.[FVERDC], origen.[FMADUR], origen.[FSOBMA], origen.[FPASAD], origen.[FPATLA], origen.[EVAPLA], origen.[EVAFCA], origen.[RACPLA], origen.[SACPLA], origen.[CONRAC], origen.[CONCAL], origen.[FRUTAR], origen.[FRUTAS], origen.[REFDOC], origen.[REFPES], origen.[FECENV], origen.[MARMOD], origen.[USUMOD], origen.[FECMOD], origen.[NUMTIK], origen.[PAGINM], origen.[NOPEDI], origen.[FEPEDI], origen.[FECFAC], origen.[CERTIF], origen.[MODEL], origen.[PROSUS], origen.[CERRSP], origen.[SUSRSP], origen.[ISCCOR], origen.[RSPCOR], origen.[BOLVEN], origen.[CARAC2], origen.[CARAC3], origen.[CARAC5], origen.[CARAC6], origen.[CARAC7], origen.[DIGIT1], origen.[DIGIT5], origen.[DIGIT6], origen.[DIGIT7], origen.[PEROPR], origen.[SEMAN], origen.[MESC], origen.[AÑOC], origen.[USUARI], origen.[PAGARA], origen.[HORAB], origen.[HORAT], origen.[FECHAT], origen.[FECHAB], origen.[IDING], origen.[IDSAL], origen.Repeticiones, origen.HashDiff, @RunId)
    WHEN NOT MATCHED BY SOURCE AND destino.EsVigente = 1
                              AND (@VentanaDesde IS NULL OR destino.FECDOC >= @VentanaDesde) THEN
        UPDATE SET EsVigente = 0, FechaUltimoCambio = SYSDATETIME(), FechaCargaInt = SYSDATETIME(), RunId = @RunId
    OUTPUT $action, inserted.EsVigente INTO #AccionesMerge;

    DECLARE @Ins INT = (SELECT COUNT(*) FROM #AccionesMerge WHERE Accion = 'INSERT');
    DECLARE @Act INT = (SELECT COUNT(*) FROM #AccionesMerge WHERE Accion = 'UPDATE' AND EsVigente = 1);
    DECLARE @Baj INT = (SELECT COUNT(*) FROM #AccionesMerge WHERE Accion = 'UPDATE' AND EsVigente = 0);

    SELECT
        @FilasLeidas                   AS FilasLeidas,
        @Ins                           AS FilasInsertadas,
        @Act                           AS FilasActualizadas,
        @Llaves - @Ins - @Act          AS FilasIgnoradas,
        @Baj                           AS FilasDadasDeBaja,
        @FilasLeidas - @Llaves         AS FilasRepetidas,
        0                              AS FilasSinFecha;

    DROP TABLE #Origen;
END
GO
