-- 233: dw.factSanAlejoFruta -- hecho Gold del dominio SanAlejo (SCD Tipo 1: una fila = estado actual del
-- documento), a partir de [int].factSanAlejoFruta: fruta de palma (FFB) recibida en las extractoras: una fila por boleta de bascula, con la calidad
-- del racimo (verde, maduro, sobremaduro...), lotes, vagones, finca y productor independiente.
--
-- Llave de negocio CodigoEmpresa + NumeroDocumento. FrutaKey es estable: el MERGE nunca borra; los
-- documentos que desaparecen del AS400 quedan con EsVigente = 0.
-- Llaves de dimension (LEFT JOIN, NULL si el codigo no esta en el catalogo): EmpresaKey, SanAlejoProductoKey, SanAlejoLocalizacionKey, SanAlejoTransportistaKey, SanAlejoClienteKey, SanAlejoProductorKey, SanAlejoFincaKey.
-- Pesos en kg tal cual del origen (la descripcion del AS400 dice T.M.): PesoNeto = PesoBruto - PesoTara.
-- Hay ~1 dia de rezago: las boletas del dia viven en PIDSA.SPVTRA* hasta que se cierran.

IF NOT EXISTS (
    SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = 'dw' AND t.name = 'factSanAlejoFruta'
)
BEGIN
    CREATE TABLE dw.factSanAlejoFruta (
        FrutaKey                   INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_dw_factSanAlejoFruta PRIMARY KEY,
        EmpresaKey                 INT            NULL CONSTRAINT FK_dw_factSanAlejoFruta_EmpresaKey REFERENCES dw.dimEmpresas(EmpresaKey),
        SanAlejoProductoKey        INT            NULL CONSTRAINT FK_dw_factSanAlejoFruta_SanAlejoProductoKey REFERENCES dw.dimSanAlejoProducto(SanAlejoProductoKey),
        SanAlejoLocalizacionKey    INT            NULL CONSTRAINT FK_dw_factSanAlejoFruta_SanAlejoLocalizacionKey REFERENCES dw.dimSanAlejoLocalizacion(SanAlejoLocalizacionKey),
        SanAlejoTransportistaKey   INT            NULL CONSTRAINT FK_dw_factSanAlejoFruta_SanAlejoTransportistaKey REFERENCES dw.dimSanAlejoTransportista(SanAlejoTransportistaKey),
        SanAlejoClienteKey         INT            NULL CONSTRAINT FK_dw_factSanAlejoFruta_SanAlejoClienteKey REFERENCES dw.dimSanAlejoCliente(SanAlejoClienteKey),
        SanAlejoProductorKey       INT            NULL CONSTRAINT FK_dw_factSanAlejoFruta_SanAlejoProductorKey REFERENCES dw.dimSanAlejoProductor(SanAlejoProductorKey),
        SanAlejoFincaKey           INT            NULL CONSTRAINT FK_dw_factSanAlejoFruta_SanAlejoFincaKey REFERENCES dw.dimSanAlejoFinca(SanAlejoFincaKey),
        CodigoEmpresa              INT            NOT NULL,
        NumeroDocumento            BIGINT         NOT NULL,
        CodigoSucursal             INT            NULL,
        NumeroId                   BIGINT         NULL,
        FechaDocumento             DATE           NULL,
        HoraDocumento              TIME(0)        NULL,
        CodigoFinca                NVARCHAR(5)    NULL,
        CodigoCapataz              NVARCHAR(5)    NULL,
        Lote1                      NVARCHAR(5)    NULL,
        RacimosLote1               DECIMAL(6,0)   NULL,
        SueltaLote1                DECIMAL(7,2)   NULL,
        Lote2                      NVARCHAR(5)    NULL,
        RacimosLote2               DECIMAL(6,0)   NULL,
        SueltaLote2                DECIMAL(7,2)   NULL,
        Lote3                      NVARCHAR(5)    NULL,
        RacimosLote3               DECIMAL(6,0)   NULL,
        SueltaLote3                DECIMAL(7,2)   NULL,
        Lote4                      NVARCHAR(5)    NULL,
        RacimosLote4               DECIMAL(6,0)   NULL,
        SueltaLote4                DECIMAL(7,2)   NULL,
        Lote5                      NVARCHAR(5)    NULL,
        RacimosLote5               DECIMAL(6,0)   NULL,
        SueltaLote5                DECIMAL(7,2)   NULL,
        Lote6                      NVARCHAR(5)    NULL,
        RacimosLote6               DECIMAL(6,0)   NULL,
        AliasVagon1                NVARCHAR(4)    NULL,
        MallaVagon1                NVARCHAR(1)    NULL,
        AliasVagon2                NVARCHAR(4)    NULL,
        MallaVagon2                NVARCHAR(1)    NULL,
        AliasVagon3                NVARCHAR(4)    NULL,
        MallaVagon3                NVARCHAR(1)    NULL,
        AliasVagon4                NVARCHAR(4)    NULL,
        MallaVagon4                NVARCHAR(1)    NULL,
        AliasVagon5                NVARCHAR(4)    NULL,
        MallaVagon5                NVARCHAR(1)    NULL,
        LlenoVagon1                NVARCHAR(1)    NULL,
        LlenoVagon2                NVARCHAR(1)    NULL,
        LlenoVagon3                NVARCHAR(1)    NULL,
        LlenoVagon4                NVARCHAR(1)    NULL,
        LlenoVagon5                NVARCHAR(1)    NULL,
        PesoVagon1                 DECIMAL(9,2)   NULL,
        PesoVagon2                 DECIMAL(9,2)   NULL,
        PesoVagon3                 DECIMAL(9,2)   NULL,
        PesoVagon4                 DECIMAL(9,2)   NULL,
        PesoVagon5                 DECIMAL(9,2)   NULL,
        CodigoProductor            INT            NULL,
        CodigoCliente              INT            NULL,
        CodigoLocalizacion         INT            NULL,
        SectorProductor            NVARCHAR(4)    NULL,
        CuentaContable             NVARCHAR(20)   NULL,
        Placa                      NVARCHAR(9)    NULL,
        NombreVendedor             NVARCHAR(30)   NULL,
        Conductor                  NVARCHAR(30)   NULL,
        CodigoProducto             NVARCHAR(5)    NULL,
        TipoFruta                  NVARCHAR(1)    NULL,
        Procedencia                NVARCHAR(1)    NULL,
        Comentario1                NVARCHAR(50)   NULL,
        Comentario2                NVARCHAR(50)   NULL,
        CodigoTransportista        INT            NULL,
        Ubicacion                  NVARCHAR(1)    NULL,
        PesoBruto                  DECIMAL(7,0)   NULL,
        PesoTara                   DECIMAL(7,0)   NULL,
        PesoNeto                   DECIMAL(7,0)   NULL,
        FrutaSuelta                DECIMAL(7,0)   NULL,
        VerdeDuro                  DECIMAL(5,0)   NULL,
        VerdeCholoton              DECIMAL(5,0)   NULL,
        Maduro                     DECIMAL(5,0)   NULL,
        SobreMaduro                DECIMAL(5,0)   NULL,
        Pasado                     DECIMAL(5,0)   NULL,
        PataLarga                  DECIMAL(5,0)   NULL,
        Raquis                     DECIMAL(5,0)   NULL,
        RacimosDevueltos           DECIMAL(5,0)   NULL,
        Eficiencia                 DECIMAL(5,0)   NULL,
        FincaVerdeDuro             DECIMAL(5,0)   NULL,
        FincaVerdeCholoton         DECIMAL(5,0)   NULL,
        FincaMaduro                DECIMAL(5,0)   NULL,
        FincaSobreMaduro           DECIMAL(5,0)   NULL,
        FincaPasado                DECIMAL(5,0)   NULL,
        FincaPataLarga             DECIMAL(5,0)   NULL,
        EvaluadorPlanta            INT            NULL,
        EvaluadorFinca             INT            NULL,
        RacimosPlanta              DECIMAL(7,0)   NULL,
        SacosPlanta                DECIMAL(7,0)   NULL,
        ContarRacimos              NVARCHAR(1)    NULL,
        ControlarCalidad           NVARCHAR(1)    NULL,
        PesoFrutaRacimo            DECIMAL(7,0)   NULL,
        PesoFrutaSuelta            DECIMAL(7,0)   NULL,
        DocumentoReferencia        BIGINT         NULL,
        PesoEnvioOrigen            DECIMAL(7,0)   NULL,
        FechaEnvioOrigen           DATE           NULL,
        MarcaModificada            NVARCHAR(1)    NULL,
        UsuarioModifico            NVARCHAR(10)   NULL,
        FechaModificacion          DATE           NULL,
        NumeroControl              NVARCHAR(10)   NULL,
        PagoInmediato              NVARCHAR(1)    NULL,
        NumeroEnvio                BIGINT         NULL,
        FechaEnvio                 DATE           NULL,
        FechaFactura               DATE           NULL,
        Certificada                NVARCHAR(2)    NULL,
        ModeloCertificacion        NVARCHAR(5)    NULL,
        ProductoSustentable        NVARCHAR(2)    NULL,
        CertificadaRSPO            NVARCHAR(2)    NULL,
        SustentableRSPO            NVARCHAR(2)    NULL,
        CorrelativoISCC            DECIMAL(20,0)  NULL,
        CorrelativoRSPO            DECIMAL(20,0)  NULL,
        BoletaVenta                DECIMAL(20,0)  NULL,
        CampoTexto2                NVARCHAR(20)   NULL,
        CampoTexto3                NVARCHAR(20)   NULL,
        CampoTexto5                NVARCHAR(20)   NULL,
        CampoTexto6                NVARCHAR(20)   NULL,
        CampoTexto7                NVARCHAR(20)   NULL,
        CampoNumerico1             DECIMAL(15,2)  NULL,
        CampoNumerico5             DECIMAL(15,0)  NULL,
        CampoNumerico6             DECIMAL(15,0)  NULL,
        CampoNumerico7             DECIMAL(15,0)  NULL,
        PeriodoOperativo           INT            NULL,
        SemanaProceso              INT            NULL,
        MesContable                INT            NULL,
        AnioContable               INT            NULL,
        Usuario                    NVARCHAR(10)   NULL,
        PagarA                     BIGINT         NULL,
        HoraBruto                  TIME(0)        NULL,
        HoraTara                   TIME(0)        NULL,
        FechaTara                  DATE           NULL,
        FechaBruto                 DATE           NULL,
        IdEntrada                  BIGINT         NULL,
        IdSalida                   BIGINT         NULL,
        Repeticiones               INT            NOT NULL,
        EsVigente                  BIT            NOT NULL CONSTRAINT DF_dw_factSanAlejoFruta_EsVigente DEFAULT (1),
        HashDiff                   BINARY(32)     NOT NULL,
        FechaAlta                  DATETIME2(7)   NOT NULL,
        FechaUltimoCambio          DATETIME2(7)   NULL,
        FechaCargaDw               DATETIME2(7)   NOT NULL CONSTRAINT DF_dw_factSanAlejoFruta_FechaCargaDw DEFAULT (SYSDATETIME()),
        RunId                      INT            NULL,
        CONSTRAINT UQ_dw_factSanAlejoFruta_Documento UNIQUE (CodigoEmpresa, NumeroDocumento)
    );
    CREATE INDEX IX_dw_factSanAlejoFruta_FechaDocumento ON dw.factSanAlejoFruta (FechaDocumento);
END
GO
