IF NOT EXISTS (
    SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = 'stg' AND t.name = 'dimVehiculo'
)
BEGIN
    CREATE TABLE stg.dimVehiculo (
    [CMID] NVARCHAR(2) NULL,
    [CMCARR] NVARCHAR(6) NULL,
    [CMCDES] NVARCHAR(30) NULL,
    [CMXDES] NVARCHAR(50) NULL,
    [CMADR1] NVARCHAR(50) NULL,
    [CMADR2] NVARCHAR(50) NULL,
    [CMSTCD] NVARCHAR(3) NULL,
    [CMPSCD] NVARCHAR(10) NULL,
    [CMCNTY] NVARCHAR(4) NULL,
    [CMSHPC] DECIMAL(15,2) NULL,
    [CMPERR] DECIMAL(1,0) NULL,
    [CMVEND] DECIMAL(8,0) NULL,
    [CMINVF] NVARCHAR(1) NULL,
    [CMLUSR] NVARCHAR(10) NULL,
    [CMLDTE] DECIMAL(8,0) NULL,
    [CMLTME] DECIMAL(6,0) NULL,
    [CMADR5] NVARCHAR(50) NULL,
    [CMADR6] NVARCHAR(50) NULL,
    [CMATTN] NVARCHAR(30) NULL,
    [CMDATN] NVARCHAR(50) NULL,
    [CMPHON] NVARCHAR(25) NULL,
    [CMFRCC] NVARCHAR(2) NULL,
    [FechaCargaStg] DATETIME2(7) NOT NULL CONSTRAINT DF_dimVehiculo_FechaCargaStg DEFAULT (SYSDATETIME()),
    [RunId] INT NULL
    );
END
