IF NOT EXISTS (
    SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = 'stg' AND t.name = 'dimProveedor'
)
BEGIN
    CREATE TABLE stg.dimProveedor (
    [VENDOR] DECIMAL(8,0) NULL,
    [VNDNAM] NVARCHAR(50) NULL,
    [VNALPH] NVARCHAR(10) NULL,
    [VNDAD1] NVARCHAR(50) NULL,
    [VNDAD2] NVARCHAR(50) NULL,
    [VSTATE] NVARCHAR(3) NULL,
    [VCOUN] NVARCHAR(4) NULL,
    [VTYPE] NVARCHAR(4) NULL,
    [VCMPNY] DECIMAL(2,0) NULL,
    [VTERMS] NVARCHAR(2) NULL,
    [VPAYTO] DECIMAL(8,0) NULL,
    [VCURR] NVARCHAR(3) NULL,
    [VPAYTY] NVARCHAR(1) NULL,
    [V1TIME] NVARCHAR(1) NULL,
    [VCON] NVARCHAR(30) NULL,
    [VPHONE] NVARCHAR(25) NULL,
    [VTAX] NVARCHAR(1) NULL,
    [VTAXCD] NVARCHAR(5) NULL,
    [VMIDNM] NVARCHAR(12) NULL,
    [V1099] NVARCHAR(1) NULL,
    [V1099C] NVARCHAR(9) NULL,
    [VDTLPD] DECIMAL(8,0) NULL,
    [VPYTYR] DECIMAL(15,2) NULL,
    [VDPURS] DECIMAL(15,2) NULL,
    [VHOLD] NVARCHAR(1) NULL,
    [VNSTAT] NVARCHAR(1) NULL,
    [VMBANK] NVARCHAR(3) NULL,
    [VMBNKC] NVARCHAR(10) NULL,
    [VMBRNO] NVARCHAR(25) NULL,
    [VMBNKA] NVARCHAR(25) NULL,
    [VMCARR] NVARCHAR(6) NULL,
    [VMMNTR] NVARCHAR(4) NULL,
    [VMLANG] NVARCHAR(3) NULL,
    [FechaCargaStg] DATETIME2(7) NOT NULL CONSTRAINT DF_dimProveedor_FechaCargaStg DEFAULT (SYSDATETIME()),
    [RunId] INT NULL
    );
END
