IF NOT EXISTS (
    SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE s.name = 'stg' AND t.name = 'factEnvios'
)
BEGIN
    CREATE TABLE stg.factEnvios (
    [ENCENV] DECIMAL(8,0) NULL,
    [ENCUSU] NVARCHAR(10) NULL,
    [ENCDSP] NVARCHAR(10) NULL,
    [ENCFEC] DECIMAL(8,0) NULL,
    [ENCTIM] DECIMAL(8,0) NULL,
    [ENCCAM] NVARCHAR(6) NULL,
    [ENCPEC] DECIMAL(15,3) NULL,
    [ENCCAD] NVARCHAR(30) NULL,
    [ENCEMT] DECIMAL(5,0) NULL,
    [ENCEMN] NVARCHAR(30) NULL,
    [ENCEN1] DECIMAL(5,0) NULL,
    [ENCED1] NVARCHAR(30) NULL,
    [ENCEN2] DECIMAL(5,0) NULL,
    [ENCED2] NVARCHAR(30) NULL,
    [ENCEN3] DECIMAL(5,0) NULL,
    [ENCED3] NVARCHAR(30) NULL,
    [ENCEN4] DECIMAL(5,0) NULL,
    [ENCED4] NVARCHAR(30) NULL,
    [ENCROU] NVARCHAR(6) NULL,
    [ENCDER] NVARCHAR(30) NULL,
    [ENCFEU] DECIMAL(8,0) NULL,
    [ENCTIU] DECIMAL(8,0) NULL,
    [ENCSTA] NVARCHAR(1) NULL,
    [ENCPES] DECIMAL(9,3) NULL,
    [ENCPLA] NVARCHAR(10) NULL,
    [ENCDT1] NVARCHAR(30) NULL,
    [ENCPT2] NVARCHAR(30) NULL,
    [FechaCargaStg] DATETIME2(7) NOT NULL CONSTRAINT DF_factEnvios_FechaCargaStg DEFAULT (SYSDATETIME()),
    [RunId] INT NULL
    );
END
